/* Generated by scripts/build_content.py. Do not edit by hand. */
window.SITE = {
 "meta": {
  "title": "Vibhor Mathur — Creative Leader",
  "description": "Vibhor Mathur is a creative leader and in-house studio builder. Brand films, campaigns and AI-native production at Razorpay, formerly Grofers."
 },
 "hero": {
  "name_line_1": "Vibhor",
  "name_line_2": "Mathur",
  "meta_left": "Creative leader. Brand films, campaigns and AI-native production, built in-house.",
  "meta_right": "Razorpay\nBengaluru, IN",
  "slides": [
   {
    "image": "assets/img/p/hero-trial.jpg"
   },
   {
    "image": "assets/img/p/hero-t20.jpg"
   },
   {
    "image": "assets/img/p/hero-stadium.jpg"
   }
  ]
 },
 "statement": {
  "text": "I turn *one photograph* into a full production, and a handful of designers into a *studio* that ships it.",
  "left": "Communication Design Senior Manager, Razorpay.",
  "right": "Previously Associate Director, Marketing Design at Grofers (now Blinkit)."
 },
 "work": {
  "title": "Selected work",
  "more_title": "More work",
  "all_label": "All work"
 },
 "tools": {
  "title": "Built in-house. *Run* by the whole studio.",
  "sub": "Four AI production tools the Razorpay design team built, and uses on live campaigns.",
  "items": [
   {
    "name": "Cinematography Tool",
    "desc": "20+ lens simulations, lighting control, 100+ colour grades.",
    "stack": "Gemini Studio · Nano Banana API"
   },
   {
    "name": "Product Image Generator",
    "desc": "Virtual product photography that holds the brand together.",
    "stack": "Gemini · Nano Banana"
   },
   {
    "name": "Advanced Image Editor",
    "desc": "Continuity across angles, scenes and faces.",
    "stack": "Scene, style, light and face references"
   },
   {
    "name": "Founder Image Generator",
    "desc": "One photo in, a full campaign library out. 4K, one click.",
    "stack": "Gemini AI Studio · Nano Banana"
   }
  ]
 },
 "lab": {
  "title": "From the *lab*",
  "sub": "Art experiments made after hours: AI art, stop motion, found objects.",
  "label": "Open the Lab"
 },
 "about_teaser": {
  "lead": "Self-taught designer from Jaipur, engineer by degree. I lead Communication Design at *Razorpay*, and make art with AI, stop motion and found objects after hours.",
  "label": "More about me",
  "portrait": "assets/img/profile.png",
  "caption_left": "Vibhor Mathur",
  "caption_right": "Jaipur → Bengaluru"
 },
 "recognition": {
  "title": "Recognition",
  "items": [
   {
    "name": "Shorty Awards",
    "detail": "Winner, Generative AI · Gold Honor, Financial Services",
    "year": "2026"
   },
   {
    "name": "Kyoorius Creative Awards",
    "detail": "First List, Film Craft & Use of Technology/AI",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Gold, Most Disruptive Creative & Design Team (Razorpay)",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Silver, Most Disruptive B2B Campaign",
    "year": "2026"
   }
  ]
 },
 "contact": {
  "headline": "Let's make something *people talk about.*",
  "email": "onlyvibhor@gmail.com",
  "links": [
   {
    "label": "Behance",
    "url": "https://www.behance.net/onlyvibhor"
   },
   {
    "label": "LinkedIn",
    "url": "https://www.linkedin.com/in/onlyvibhor/"
   },
   {
    "label": "Instagram",
    "url": "https://www.instagram.com/onlyvibhor/"
   },
   {
    "label": "ADPList",
    "url": "https://adplist.org/mentors/vibhor-mathur"
   }
  ]
 }
};
window.ABOUT = {
 "meta": {
  "title": "About — Vibhor Mathur",
  "description": "Self-taught designer from Jaipur, engineer by degree. Communication Design Senior Manager at Razorpay, formerly Associate Director at Grofers. Also an artist working with AI, stop motion and found objects."
 },
 "label": "About",
 "headline": "Designing narratives by day. Crafting emotions through *art* by night.",
 "portrait": "assets/img/profile.png",
 "portrait_caption": "Jaipur → Bengaluru",
 "facts": [
  {
   "label": "Currently",
   "value": "Communication Design Senior Manager, Razorpay"
  },
  {
   "label": "Based",
   "value": "Bengaluru, India. Roots in Jaipur."
  },
  {
   "label": "Education",
   "value": "B.Tech, Computer Engineering. Government Engineering College Bikaner, 2010 to 2014."
  },
  {
   "label": "Languages",
   "value": "English, Hindi"
  }
 ],
 "numbers": [
  {
   "value": "11",
   "label": "years in consumer commerce and fintech, since March 2015"
  },
  {
   "value": "10+",
   "label": "product lines and business units on one deck design language"
  },
  {
   "value": "4",
   "label": "AI production tools built in-house and used on live campaigns"
  }
 ],
 "intro": [
  "I'm a self-taught designer from Jaipur with a degree in computer engineering. By day I make advertising and brand narratives. Outside the office I make art, mostly by turning everyday objects into small vessels of emotion and meaning.",
  "At Grofers, which became Blinkit, I spent over six years in marketing design: integrated campaigns around the app's recurring sale events, social content, app visual identities, and the hiring and development of a creative team. I left as Associate Director in October 2021.",
  "Since then I've led Communication Design at Razorpay across Payments, RazorpayX and POS. The work is brand films, keynote videos, landing pages, sales decks, social campaigns and product imagery, held together by one visual system and a way of telling stories that starts from data, consumer interviews and what past campaigns taught us.",
  "A lot of that work is now AI-native. *Trial of the Century*, the animal-courtroom film for RazorpayX Payroll, won Generative AI at the Shorty Awards. *Break To Build* turned one photograph of each of thirty founders into thirty ad films. Both ran as repeatable production systems rather than one-offs, and the design team now uses four in-house AI tools on live campaigns."
 ],
 "timeline": {
  "label": "Path",
  "items": [
   {
    "years": "Oct 2021 — Now",
    "org": "Razorpay",
    "role": "Communication Design Senior Manager · Bengaluru",
    "note": "Leads Communication Design across Payments, RazorpayX and POS: brand films, keynote videos, landing pages, sales decks, social campaigns and product imagery. Established a deck design language now used across more than ten product lines and business units."
   },
   {
    "years": "Mar 2015 — Oct 2021",
    "org": "Grofers (now Blinkit)",
    "role": "Associate Director, Marketing Design · Gurugram",
    "note": "Integrated advertising for recurring sale events, social campaigns and app visual identities. Hired and developed the creative team and directed external production partners."
   },
   {
    "years": "2010 — 2014",
    "org": "Government Engineering College Bikaner",
    "role": "B.Tech, Computer Engineering",
    "note": "Design was already happening alongside the degree: a CopyPress Infographic Designer certificate followed in December 2013."
   }
  ]
 },
 "leadership": {
  "label": "On creative leadership",
  "title": "Notes from running an in-house design team.",
  "intro": "From a 2024 post on planning the year for in-house design teams. The ideas I still work from:",
  "items": [
   {
    "title": "Keep widening the toolkit",
    "body": "Video and animation, 3D in Blender and Spline, and AI tools such as ChatGPT, Midjourney, Ideogram and Runway. Continuous learning keeps a team competitive, and engaged."
   },
   {
    "title": "Make goals measurable",
    "body": "Use analytics not only to validate creative work but to show how it contributes to the company. Aim for content that resonates, from social buzz to booklets that win over the most numbers-minded colleague."
   },
   {
    "title": "Build a culture that can take risks",
    "body": "Turn brainstorms from dreaded meetings into hubs of collaboration, where trying something bold does not mean fearing failure."
   },
   {
    "title": "Design for the business, not just the brief",
    "body": "Work in step with the brand marketing team so the output reflects company goals, not only creative ambition."
   }
  ],
  "source": {
   "label": "Read the original post",
   "url": "https://www.onlyvibhor.com/post/setting-up-design-lead-goals-for-2025"
  }
 },
 "studio": {
  "label": "After hours",
  "title": "The studio at night.",
  "body": "In my creative studio I work on AI art, stop-motion animation and found-object art, and make fun, quirky content for platforms, especially Instagram. The work runs from introspective musings to whimsical one-liners.\n\nTwo AI experiments from 2023, built on Stable Diffusion and ControlNet, live in the Lab.",
  "link": {
   "label": "Open the Lab",
   "url": "lab.html"
  }
 },
 "teaching": {
  "label": "Teaching and mentoring",
  "items": [
   {
    "name": "ADPList",
    "detail": "Design mentor. 60-minute one-to-one mentorship sessions."
   },
   {
    "name": "GrowthSchool",
    "detail": "Mentor."
   },
   {
    "name": "AI in art and design workshop",
    "detail": "Image generation, AI video and AI-assisted UI design, March 2024."
   },
   {
    "name": "AI design workshops",
    "detail": "Whole Truth Foods, Wolfkrafft."
   },
   {
    "name": "JK Lakshmipat University, Jaipur",
    "detail": "Short course on generative AI design."
   },
   {
    "name": "Conversations",
    "detail": "Designland, Groundbreakin Podcast, Design Tank, xtended Pack Collective."
   }
  ],
  "quote": {
   "text": "He felt more like an elder brother than just a mentor.",
   "who": "Vibhu Kapil, visual and motion designer, on ADPList"
  }
 },
 "recognition": {
  "label": "Recognition",
  "items": [
   {
    "name": "Shorty Awards",
    "detail": "Winner, Generative AI. Gold Honor, Financial Services. Finalist, Community Engagement.",
    "work": "Trial of the Century",
    "year": "2026"
   },
   {
    "name": "Kyoorius Creative Awards",
    "detail": "First List: Film Craft; Use of Technology & AI.",
    "work": "Trial of the Century",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Gold, Most Disruptive Creative & Design Team.",
    "work": "Razorpay",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Silver, Most Disruptive B2B Campaign.",
    "work": "Trial of the Century",
    "year": "2026"
   }
  ]
 },
 "writing": {
  "label": "Writing",
  "items": [
   {
    "title": "Embracing Creative Leadership in 2025: Strategies for In-House Design Teams",
    "date": "Apr 2024",
    "url": "https://www.onlyvibhor.com/post/setting-up-design-lead-goals-for-2025"
   },
   {
    "title": "Navigating the Frontier of Creativity: The Potential of AI in Art and Design",
    "date": "Mar 2024",
    "url": "https://www.onlyvibhor.com/post/navigating-the-frontier-of-creativity-unveiling-the-potential-of-ai-in-art-and-design"
   },
   {
    "title": "Habitats without the life",
    "date": "Dec 2023",
    "url": "https://www.onlyvibhor.com/post/habitats-without-the-life"
   },
   {
    "title": "Stable Diffusion AI and ControlNet",
    "date": "Nov 2023",
    "url": "https://www.onlyvibhor.com/post/stable-diffusion-ai-and-controlnet"
   }
  ]
 },
 "elsewhere": {
  "label": "Elsewhere",
  "items": [
   {
    "label": "Behance",
    "url": "https://www.behance.net/onlyvibhor"
   },
   {
    "label": "LinkedIn",
    "url": "https://www.linkedin.com/in/onlyvibhor/"
   },
   {
    "label": "Instagram",
    "url": "https://www.instagram.com/onlyvibhor/"
   },
   {
    "label": "YouTube",
    "url": "https://www.youtube.com/channel/UCYz6bkPGCR3gapGpoDKuSDg"
   },
   {
    "label": "X",
    "url": "https://twitter.com/onlyvibhor"
   },
   {
    "label": "ADPList",
    "url": "https://adplist.org/mentors/vibhor-mathur"
   }
  ]
 }
};
window.PROJECTS = [
 {
  "title": "Trial of the Century",
  "slug": "trial",
  "published": true,
  "featured": true,
  "order": 1,
  "title_lines": "Trial of the\nCentury",
  "card_title": "Trial of the\nCentury",
  "client": "RazorpayX Payroll",
  "year": "2025",
  "category": "AI film · Campaign",
  "role": "Art Direction",
  "tagline": "An animal courtroom puts HR's most dreaded monthly question on trial.",
  "summary": "A Panchatantra-style courtroom film that turned payslip confusion into a pop-culture moment for the HR community.",
  "cover": {
   "image": "assets/img/p/trial-1.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "2.1M+",
    "label": "impressions"
   },
   {
    "value": "1.5M+",
    "label": "unique accounts reached"
   },
   {
    "value": "8.64%",
    "label": "engagement rate, 4× the B2B fintech average"
   },
   {
    "value": "13%",
    "label": "uplift in leads during the campaign"
   },
   {
    "value": "16%",
    "label": "surge in website traffic"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Reach the HR community, a relevant audience that is notoriously hard to engage.",
    "body": "RazorpayX Payroll needed awareness among HR professionals. They are the right audience, but a finance-heavy product is a tough sell to people who rarely engage with branded content.\n\nA recent launch gave us a way in: an AI feature that lets employees talk directly to their payslips and ask salary questions. HRs showed genuine traction, which made us dig deeper into why."
   },
   {
    "type": "statement",
    "text": "For employees, Salary Day is the most anticipated day of the month. For HR, it is a week-long nightmare."
   },
   {
    "type": "text",
    "label": "The insight",
    "title": "The same questions, every month, and everyone had accepted it.",
    "body": "The moment salaries hit accounts, inboxes flood: *Why did my salary change? What is this deduction?* Not out of carelessness, but because payslips are dense with abbreviations, tax codes and compliance jargon that few people understand.\n\nOver time the dependency became normal. HRs absorbed it, employees assumed it. **That cultural resignation became our creative brief.**"
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-1.jpg",
    "caption": "Campaign overview: insight, design brief, idea and results",
    "size": "full"
   },
   {
    "type": "text",
    "label": "The idea",
    "title": "If the same questions come back every month, the system needs fixing, not the people.",
    "body": "We reframed repeated salary queries as a payroll design flaw and put the repetition on trial, in an animal courtroom inspired by the Panchatantra and an unmistakable piece of Hindi cinema, the *sawaal pe sawaal* courtroom scene from *Damini*.\n\n- **Porcumar Rao**, a porcupine, takes every recurring query like a spoke in his back.\n- **Chulbull Pandey**, the aggressive bull, channels the courtroom cross-examination.\n- **Hathiram Trankalp**, a wise elephant, presides over the chaos.\n- **The employees** appear as a flock of chirping birds.\n\nWithin the story, RazorpayX Payroll introduces R.A.Y., an AI assistant that reads the payslip and explains any change instantly, in simple language, without HR stepping in."
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-3.jpg",
    "caption": "Location design and character sheets",
    "size": "full"
   },
   {
    "type": "steps",
    "label": "The process",
    "title": "Animation-quality world-building without a single traditional animation tool.",
    "items": [
     {
      "title": "Explore",
      "body": "Character and mood explorations, iterated until the tone and personalities felt right.",
      "tools": "Midjourney"
     },
     {
      "title": "Lock the world",
      "body": "A digital map of the courtroom with every camera position fixed before a frame was generated: spatial logic instead of prompt randomness.",
      "tools": "Midjourney · Gemini · ChatGPT"
     },
     {
      "title": "Frame",
      "body": "Camera and framing prompts written with ChatGPT and Gemini, then executed through Nano Banana for consistent multi-angle shots, refined for continuity and texture.",
      "tools": "Nano Banana · Photoshop · Firefly"
     },
     {
      "title": "Animate",
      "body": "Performances generated and iterated until body language and facial expression felt natural.",
      "tools": "Kling · Runway · Google Veo"
     },
     {
      "title": "Voice",
      "body": "Professional voice actors chosen to embody each character, with lip-sync aligned to the recorded performance.",
      "tools": "Kling Lip Sync · ElevenLabs"
     },
     {
      "title": "Finish",
      "body": "Composited, edited and upscaled to 4K at 60fps.",
      "tools": "After Effects · Premiere · Topaz Labs"
     }
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-2.jpg",
    "caption": "The production workflow, from moodboard to final edit",
    "size": "wide"
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-4.jpg",
    "caption": "Animation, expression and voice direction",
    "size": "wide"
   },
   {
    "type": "video",
    "url": "https://www.youtube.com/watch?v=uDeZ0zKgVqY",
    "poster": "",
    "caption": "The film",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Beyond the film",
    "title": "We gave HRs a place to be heard, and a soundtrack.",
    "body": "**The Wall of Laughter** was an anonymous digital board where HR professionals shared the funniest salary questions they had ever received. Anonymity mattered: HR professionals are cautious about being seen online, so humour became a safe way in.\n\n**\"Inbox Avalanche\"**, a debut music single, turned the monthly flood into a hook and earned 4.5 lakh+ impressions and 50+ saves. B2B content, competing with entertainment.\n\nThe movement spread through HR communities across India, including The Shape of Work, People Matters, SHRM India, Being HR and HR Breakfast Club."
   },
   {
    "type": "metrics",
    "label": "The result",
    "items": [
     {
      "value": "2.1M+",
      "label": "impressions"
     },
     {
      "value": "135K+",
      "label": "total engagements at an 8.64% rate"
     },
     {
      "value": "300K",
      "label": "HR professionals reached, of a 650K online audience"
     },
     {
      "value": "300+",
      "label": "brand mentions"
     },
     {
      "value": "250+",
      "label": "reposts"
     },
     {
      "value": "13%",
      "label": "uplift in D&O leads"
     }
    ]
   },
   {
    "type": "text",
    "label": "The takeaway",
    "title": "The narrative shifted from \"HR failure\" to \"systemic gap\".",
    "body": "What began as a feature launch turned into a pop-culture moment inside the HR ecosystem, with startups across the space (Plum, Spring Verify, ClearTax, Smartstaff, Jify, Fi) engaging with a campaign that, for once, was about HR."
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Art Director"
   },
   {
    "name": "Sourajit Sengupta",
    "role": "Creative Director"
   },
   {
    "name": "Saurabh Soni",
    "role": "Vice President, Design"
   },
   {
    "name": "Apuarv Sethi",
    "role": "Vice President, Marketing"
   },
   {
    "name": "Subhash Dawda",
    "role": "Marketing, RazorpayX"
   },
   {
    "name": "Priyank Hegde",
    "role": "Design"
   },
   {
    "name": "Rahul Girish",
    "role": "Design"
   },
   {
    "name": "Aadithya Narayanan S",
    "role": "Design"
   },
   {
    "name": "Siddhant Tiwari",
    "role": "Design"
   },
   {
    "name": "Othneil Dutta",
    "role": "Design"
   },
   {
    "name": "Nihar Gopal Lohiya",
    "role": "Marketing"
   },
   {
    "name": "Nikita Pinto",
    "role": "Marketing"
   },
   {
    "name": "Sushmit Sengupta",
    "role": "Marketing"
   },
   {
    "name": "Nivedita Prabhu",
    "role": "Marketing"
   },
   {
    "name": "Gurnain Kaur Gopal Singh Thapar",
    "role": "Marketing"
   },
   {
    "name": "Gurunicketan S",
    "role": "Content"
   }
  ],
  "awards": [
   {
    "title": "Shorty Awards",
    "detail": "Winner, Generative AI"
   },
   {
    "title": "Shorty Awards",
    "detail": "Gold Honor, Financial Services"
   },
   {
    "title": "Shorty Awards",
    "detail": "Finalist, Community Engagement"
   },
   {
    "title": "Kyoorius Creative Awards 2026",
    "detail": "First List: Film Craft; Use of Technology & AI"
   },
   {
    "title": "ET Brand Disruption Awards 2026",
    "detail": "Silver, Most Disruptive B2B Campaign"
   }
  ],
  "links": [
   {
    "label": "Watch the film",
    "url": "https://www.youtube.com/watch?v=uDeZ0zKgVqY"
   },
   {
    "label": "Shorty Awards entry",
    "url": "https://shortyawards.com/18th/razorpayx-trial-of-the-century"
   },
   {
    "label": "Kyoorius listing",
    "url": "https://winners.kyoorius.com/winners/2026/kca/13684-trial-of-the-century/"
   },
   {
    "label": "Wall of Laughter",
    "url": "https://razorpayxwalloflaughter.razorpay.com/"
   },
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254333269/Trial-of-the-century"
   }
  ],
  "categories": [
   "AI Film",
   "Campaign"
  ],
  "external_url": ""
 },
 {
  "title": "Break To Build",
  "slug": "btb",
  "published": true,
  "featured": true,
  "order": 2,
  "title_lines": "Break\nTo Build",
  "card_title": "Break\nTo Build",
  "client": "Razorpay × JioHotstar",
  "year": "2026",
  "category": "AI film · IPL campaign",
  "role": "Art & Creative Direction",
  "tagline": "Thirty founders. Thirty ad films. Zero shoots.",
  "summary": "A 100% AI experiment in making a TVC: founders photographed once, then broken, bent and built into cinematic films.",
  "cover": {
   "image": "assets/img/p/btb-1.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "30",
    "label": "AI-led ad films"
   },
   {
    "value": "30",
    "label": "founders featured"
   },
   {
    "value": "1",
    "label": "photograph per founder"
   },
   {
    "value": "0",
    "label": "live-action shoots"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Back the founders building India, on the biggest stage in Indian marketing.",
    "body": "Razorpay's IPL 2026 push on JioHotstar. The ambition was to match the scale and spectacle of the tournament, while also stress-testing everything the design team had learned about AI workflows, tooling and design systems over the year."
   },
   {
    "type": "statement",
    "text": "A 100% AI experiment in making a TVC. No actors. No stunts. No live-action shots."
   },
   {
    "type": "image",
    "image": "assets/img/p/btb-1.jpg",
    "caption": "Break To Build, Razorpay 2026",
    "size": "full"
   },
   {
    "type": "text",
    "label": "The launch film",
    "title": "What if breaking through was literal?",
    "body": "We took the campaign idea of breaking through and turned it into a visual statement: breaking, bending and defying the impossible."
   },
   {
    "type": "text",
    "label": "The problem",
    "title": "Getting 30 busy founders in one frame? Almost impossible.",
    "body": "A shoot at this scale means complex schedules and a massive production budget. Breaking glass, breaking walls, breaking ceilings means high-risk shots, high production costs, and founders who are not actors.\n\n**AI made it possible. Thirty founders. One frame. Zero logistics.**"
   },
   {
    "type": "image",
    "image": "assets/img/p/btb-4.jpg",
    "caption": "30 founders. 30 stories. One unusual production.",
    "size": "wide"
   },
   {
    "type": "steps",
    "label": "From a photoshoot to a TV commercial",
    "title": "One shoot and AI. Infinite possibilities.",
    "items": [
     {
      "title": "Shoot",
      "body": "Founders photographed once across carefully planned angles and poses."
     },
     {
      "title": "Style frames",
      "body": "We designed the visual language and built the worlds each founder would break through."
     },
     {
      "title": "Generate",
      "body": "AI transformed stills into cinematic environments, action and destruction."
     },
     {
      "title": "Craft",
      "body": "Shots were refined, composited and edited into finished films."
     }
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/btb-9.jpg",
    "caption": "From internal shoot, to planned poses, to worlds, to finished films",
    "size": "narrow"
   },
   {
    "type": "text",
    "label": "The takeaway",
    "title": "A stress test for everything the team had learned about AI.",
    "body": "Thirty ad films, a launch film, teasers, music and supporting content, produced AI-led from end to end: not AI-assisted, not AI-enhanced. It took collective conviction to say yes to something with no established playbook, on one of the biggest stages in Indian marketing."
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Art & Creative Direction"
   },
   {
    "name": "Rahul Girish",
    "role": "Design"
   },
   {
    "name": "Sourajit Sengupta",
    "role": "Creative Director"
   },
   {
    "name": "Varun Thakar",
    "role": "Partner"
   },
   {
    "name": "Talented.Agency",
    "role": "Partner"
   },
   {
    "name": "Neil Dutta",
    "role": ""
   },
   {
    "name": "Akash Wadhwa",
    "role": ""
   },
   {
    "name": "Sanjana Shetty",
    "role": ""
   },
   {
    "name": "Ishan Gupta",
    "role": ""
   },
   {
    "name": "Aadithya Narayanan S",
    "role": ""
   },
   {
    "name": "Ajay R Nath",
    "role": ""
   },
   {
    "name": "Nivedita Prabhu",
    "role": ""
   },
   {
    "name": "Ajmal Roshan",
    "role": ""
   },
   {
    "name": "Aman Shetty",
    "role": ""
   },
   {
    "name": "Ashish Thawani",
    "role": ""
   },
   {
    "name": "MarkMedia",
    "role": "Partner"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254665051/Break-To-Build-Razorpay-IPL-Campaign"
   }
  ],
  "categories": [
   "AI Film",
   "Campaign"
  ],
  "external_url": ""
 },
 {
  "title": "Backing India's Start-Up Champions",
  "slug": "t20",
  "published": true,
  "featured": true,
  "order": 3,
  "title_lines": "Start-Up\nChampions",
  "card_title": "Start-Up\nChampions",
  "client": "Razorpay × T20 World Cup",
  "year": "2026",
  "category": "Broadcast · Print · Social",
  "role": "Art Direction",
  "tagline": "India celebrates cricketers and founders equally. Only one gets a stadium. We built one for both.",
  "summary": "81 television films, a newspaper front page and 200+ social posts for 20 founders, with no cameras, sets or lights.",
  "cover": {
   "image": "assets/img/p/t20-1.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "81",
    "label": "television films"
   },
   {
    "value": "8.1M",
    "label": "unique viewers"
   },
   {
    "value": "133%",
    "label": "increase in purchase intent"
   },
   {
    "value": "200+",
    "label": "extended social posts"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The idea",
    "title": "Put founders on the screen cricket fans are already watching.",
    "body": "The T20 World Cup season is when the nation watches together. Razorpay set out to back its start-up champions where attention already was, treating founders the way the country treats cricketers: with a stadium, a jersey and a player card."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-1.jpg",
    "caption": "Backing India's Start-Up Champions",
    "size": "full"
   },
   {
    "type": "statement",
    "text": "Viewers didn't see an ad. They saw a founder who belonged on that screen."
   },
   {
    "type": "text",
    "label": "TV ads",
    "title": "Designed to look like the broadcast, not interrupt it.",
    "body": "**81 films. 20 match dates. Zero shoots.** Each founder was lit three ways, warm daylight, floodlit blue and night drama, matched to every match slot.\n\nEvery film mirrored cricket player-card aesthetics: centre-composed, sportsman poses, stadium environment."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-5.jpg",
    "caption": "Television: lower-thirds, player cards and three lighting environments",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "The pipeline",
    "title": "20 founders. One photo each. No shoots, no studios, no waiting.",
    "body": "A custom avatar tool, built on the Nano Banana API and Gemini AI Studio, took a single reference image and returned a full campaign visual library: sportsman poses, campaign costume, expressions tuned to each founder's personality. 4K output, one click.\n\nEvery founder walked into the campaign looking like they had always belonged on that stage."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-4.jpg",
    "caption": "The custom avatar generation tool",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Social",
    "title": "Every founder. Every platform. One pipeline.",
    "body": "200+ extended social posts carried the campaign forward, including founders who did not appear in the TV spots. Drop in a founder photo and their business story and the pipeline returns a fully composed, campaign-ready post: title layouts per personality, costume, pose, lighting and background, all handled.\n\nNo individual design sessions. No back and forth. Just output."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Gemini",
     "Nano Banana",
     "Replit",
     "ChatGPT",
     "Banner Bear"
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-6.jpg",
    "caption": "Social content generation",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Print",
    "title": "The nation reads the paper. We put founders on the front page.",
    "body": "The same pipeline that built the TV assets produced full-page newspaper ads: same founder, same costume, same campaign language, in the hands of the same audience the morning after the match."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-7.jpg",
    "caption": "Print: founders on the front page",
    "size": "wide"
   },
   {
    "type": "image_grid",
    "columns": 1,
    "images": [
     {
      "image": "assets/img/p/t20-3.jpg",
      "caption": "81 ad films, 1 newspaper ad, 200+ social posts. No cameras. No sets. No lights."
     },
     {
      "image": "assets/img/p/t20-2.jpg",
      "caption": "Results"
     }
    ]
   },
   {
    "type": "metrics",
    "label": "The result",
    "items": [
     {
      "value": "450K+",
      "label": "CTV impressions"
     },
     {
      "value": "8.1M",
      "label": "unique viewers"
     },
     {
      "value": "928K",
      "label": "LinkedIn impressions"
     },
     {
      "value": "133%",
      "label": "purchase intent up"
     }
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Art Direction"
   },
   {
    "name": "Razorpay Communication Design",
    "role": "Design"
   },
   {
    "name": "Razorpay Marketing",
    "role": "Marketing"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254656865/Backing-Indias-Start-Up-Champions-T20-Campaign"
   }
  ],
  "categories": [
   "AI Film",
   "Campaign",
   "Social",
   "Print"
  ],
  "external_url": ""
 },
 {
  "title": "Magic Checkout Landing Page",
  "slug": "magic-checkout",
  "published": true,
  "featured": false,
  "order": 5,
  "title_lines": "Magic Checkout Landing Page",
  "card_title": "Magic Checkout Landing Page",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Landing Page / Web"
  ],
  "external_url": "https://www.behance.net/gallery/254362459/Magic-Checkout-Landing-Page",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/254362459/Magic-Checkout-Landing-Page"
   }
  ]
 },
 {
  "title": "Agentic Commerce Engine Launch Video",
  "slug": "agentic-commerce-engine",
  "published": true,
  "featured": false,
  "order": 6,
  "title_lines": "Agentic Commerce Engine Launch Video",
  "card_title": "Agentic Commerce Engine Launch Video",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Video"
  ],
  "external_url": "https://www.behance.net/gallery/255895063/Agentic-Commerce-Engine-Launch-Video",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/255895063/Agentic-Commerce-Engine-Launch-Video"
   }
  ]
 },
 {
  "title": "International Payments Launch Video",
  "slug": "international-payments",
  "published": true,
  "featured": false,
  "order": 7,
  "title_lines": "International Payments Launch Video",
  "card_title": "International Payments Launch Video",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Video"
  ],
  "external_url": "https://www.behance.net/gallery/185746781/Razorpay-International-Payments-Launch-Video",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/185746781/Razorpay-International-Payments-Launch-Video"
   }
  ]
 },
 {
  "title": "Magic Conversations Videos",
  "slug": "magic-conversations",
  "published": true,
  "featured": false,
  "order": 8,
  "title_lines": "Magic Conversations Videos",
  "card_title": "Magic Conversations Videos",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Video"
  ],
  "external_url": "https://www.behance.net/gallery/185745413/Magic-Conversations-Videos",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/185745413/Magic-Conversations-Videos"
   }
  ]
 },
 {
  "title": "Passport For Your Products",
  "slug": "passport-for-your-products",
  "published": true,
  "featured": false,
  "order": 9,
  "title_lines": "Passport For Your Products",
  "card_title": "Passport For Your Products",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Campaign",
   "AI Film"
  ],
  "external_url": "https://www.behance.net/gallery/185756345/Passport-For-Your-Products-AI-Gen-Campaign",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/185756345/Passport-For-Your-Products-AI-Gen-Campaign"
   }
  ]
 },
 {
  "title": "MoneySaver Export Account",
  "slug": "moneysaver-export-account",
  "published": true,
  "featured": false,
  "order": 10,
  "title_lines": "MoneySaver Export Account",
  "card_title": "MoneySaver Export Account",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Campaign",
   "AI Film"
  ],
  "external_url": "https://www.behance.net/gallery/185754027/MoneySaver-Export-Account-AI-Gen-campaign",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/185754027/MoneySaver-Export-Account-AI-Gen-campaign"
   }
  ]
 },
 {
  "title": "Payments on WhatsApp",
  "slug": "payments-on-whatsapp",
  "published": true,
  "featured": false,
  "order": 11,
  "title_lines": "Payments on WhatsApp",
  "card_title": "Payments on WhatsApp",
  "client": "Razorpay",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Campaign"
  ],
  "external_url": "https://www.behance.net/gallery/185779105/Razorpay-Payments-on-WhatsApp",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/185779105/Razorpay-Payments-on-WhatsApp"
   }
  ]
 },
 {
  "title": "Grofers Logo Guidelines",
  "slug": "grofers-logo-guidelines",
  "published": true,
  "featured": false,
  "order": 12,
  "title_lines": "Grofers Logo Guidelines",
  "card_title": "Grofers Logo Guidelines",
  "client": "Grofers",
  "year": "",
  "category": "",
  "role": "",
  "tagline": "",
  "summary": "",
  "categories": [
   "Brand & Identity"
  ],
  "external_url": "https://www.behance.net/gallery/123079157/grofers-logo-guidelines",
  "cover": {
   "image": "",
   "video": ""
  },
  "metrics": [],
  "sections": [],
  "team": [],
  "awards": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/123079157/grofers-logo-guidelines"
   }
  ]
 }
];
window.EXPERIMENTS = [
 {
  "title": "Habitats without the life",
  "slug": "habitats",
  "published": true,
  "order": 1,
  "year": "2023",
  "medium": [
   "AI art"
  ],
  "tools": "Stable Diffusion, ControlNet",
  "title_lines": "Habitats\nwithout\nthe life",
  "tagline": "Landscapes that carry the silhouette of the creatures that belong in them.",
  "summary": "AI landscapes built from animal silhouettes with Stable Diffusion and ControlNet.",
  "cover": {
   "image": "assets/img/lab/habitats-02.jpg",
   "video": ""
  },
  "external_url": "",
  "sections": [
   {
    "type": "text",
    "label": "The idea",
    "title": "Wildlife and habitat are one picture.",
    "body": "A visual representation of the interconnectedness between wildlife and their habitats, and a reminder of the delicate balance of our ecosystems.\n\nUsing Stable Diffusion and its ControlNet feature, I made landscapes that blend the essence of iconic creatures with their natural environments."
   },
   {
    "type": "text",
    "label": "The method",
    "title": "Start from a silhouette, grow a landscape.",
    "body": "The control images are plain black-and-white silhouettes: a bear, a camel, an elephant and a rhino. Each generated landscape sits next to the shape it was built from, so you can see how the creature's outline organises the terrain."
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-01.jpg",
      "caption": "Bear: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-02.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-03.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-04.jpg",
      "caption": "Camel: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-05.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-06.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-07.jpg",
      "caption": "Elephant: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-08.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-09.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-10.jpg",
      "caption": "Rhino: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-11.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-12.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "tools",
    "label": "Tools",
    "items": [
     "Stable Diffusion",
     "ControlNet"
    ]
   }
  ],
  "links": [
   {
    "label": "Original post (Dec 2023)",
    "url": "https://www.onlyvibhor.com/post/habitats-without-the-life"
   }
  ]
 },
 {
  "title": "Absolut Landscapes",
  "slug": "absolut",
  "published": true,
  "order": 2,
  "year": "2023",
  "medium": [
   "AI art"
  ],
  "tools": "SMUGO.ai, Stable Diffusion, ControlNet (Canny)",
  "title_lines": "Absolut\nLandscapes",
  "tagline": "A modern AI take on a campaign built around one bottle shape.",
  "summary": "Landscapes shaped by the Absolut bottle, made with Stable Diffusion and ControlNet.",
  "cover": {
   "image": "assets/img/lab/absolut-4.jpg",
   "video": ""
  },
  "external_url": "",
  "sections": [
   {
    "type": "text",
    "label": "The reference",
    "title": "Absolut has built a campaign around one shape for decades.",
    "body": "Absolut Vodka's long-running advertising features the distinctive shape of its bottle, promoting artistic interpretations of it. Its collaborations with visual artists date back to the 1980s, and Andy Warhol once said: *\"I love the bottle. I'd like to do something.\"*\n\nA modern AI version of the idea felt like the obvious next experiment. This is a personal exploration inspired by that campaign."
   },
   {
    "type": "text",
    "label": "The method",
    "title": "The bottle becomes the structure.",
    "body": "I used SMUGO.ai, a free platform with an interface close to Automatic1111 that offers Stable Diffusion's img2img, ControlNet and HiResFix.\n\nThe shape of the bottle went into ControlNet using the Canny processor, with some prompt engineering on top. The images are low resolution because I did not have access to my own PC when I made them."
   },
   {
    "type": "image_grid",
    "columns": "2",
    "images": [
     {
      "image": "assets/img/lab/absolut-1.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-2.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-3.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-4.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-5.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-6.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-7.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-8.jpg",
      "caption": ""
     }
    ]
   },
   {
    "type": "tools",
    "label": "Tools",
    "items": [
     "SMUGO.ai",
     "Stable Diffusion",
     "ControlNet (Canny)",
     "img2img",
     "HiResFix"
    ]
   }
  ],
  "links": [
   {
    "label": "Original post (Nov 2023)",
    "url": "https://www.onlyvibhor.com/post/stable-diffusion-ai-and-controlnet"
   }
  ]
 },
 {
  "title": "AI Experiments",
  "slug": "ai-experiments",
  "published": true,
  "order": 3,
  "year": "",
  "medium": [
   "AI art"
  ],
  "tools": "",
  "title_lines": "AI\nExperiments",
  "tagline": "",
  "summary": "",
  "cover": {
   "image": "",
   "video": ""
  },
  "external_url": "https://www.behance.net/gallery/185757595/AI-Experiments",
  "sections": [],
  "links": [
   {
    "label": "View on Behance",
    "url": "https://www.behance.net/gallery/185757595/AI-Experiments"
   }
  ]
 }
];
