/* Generated by scripts/build_content.py. Do not edit by hand. */
window.SITE = {
 "meta": {
  "title": "Vibhor Mathur — Creative Leader",
  "description": "Vibhor Mathur is a creative leader and in-house studio builder. Brand films, campaigns and AI-native production at Razorpay, formerly Grofers."
 },
 "hero": {
  "name_line_1": "Vibhor",
  "name_line_2": "Mathur",
  "meta_left": "Creative leader. Brand films, campaigns and AI-native production, built in-house.",
  "meta_right": "Razorpay\nBengaluru, IN",
  "slides": [
   {
    "image": "assets/img/p/hero-trial.jpg"
   },
   {
    "image": "assets/img/p/hero-t20.jpg"
   },
   {
    "image": "assets/img/p/hero-stadium.jpg"
   }
  ]
 },
 "statement": {
  "text": "I turn *one photograph* into a full production, and a handful of designers into a *studio* that ships it.",
  "left": "Communication Design Senior Manager, Razorpay.",
  "right": "Previously Associate Director, Marketing Design at Grofers (now Blinkit)."
 },
 "work": {
  "title": "Selected work",
  "more_title": "More work",
  "all_label": "All work"
 },
 "tools": {
  "title": "Built in-house. *Run* by the whole studio.",
  "sub": "Four AI production tools the Razorpay design team built, and uses on live campaigns. The full toolkit has its own page.",
  "items": [
   {
    "name": "Cinematography Tool",
    "desc": "20+ lens simulations, lighting control, 100+ colour grades.",
    "stack": "Gemini Studio · Nano Banana API"
   },
   {
    "name": "Product Image Generator",
    "desc": "Virtual product photography that holds the brand together.",
    "stack": "Gemini · Nano Banana"
   },
   {
    "name": "Advanced Image Editor",
    "desc": "Continuity across angles, scenes and faces.",
    "stack": "Scene, style, light and face references"
   },
   {
    "name": "Founder Image Generator",
    "desc": "One photo in, a full campaign library out. 4K, one click.",
    "stack": "Gemini AI Studio · Nano Banana"
   }
  ],
  "label": "Open the AI Toolkit"
 },
 "lab": {
  "title": "From the *lab*",
  "sub": "Art experiments made after hours: AI art, stop motion, found objects.",
  "label": "Open the Lab"
 },
 "about_teaser": {
  "lead": "Self-taught designer from Jaipur, engineer by degree. I lead Communication Design at *Razorpay*, and make art with AI, stop motion and found objects after hours.",
  "label": "More about me",
  "portrait": "assets/img/profile.png",
  "caption_left": "Vibhor Mathur",
  "caption_right": "Jaipur → Bengaluru"
 },
 "recognition": {
  "title": "Recognition",
  "items": [
   {
    "name": "Shorty Awards",
    "detail": "Winner, Generative AI · Gold Honor, Financial Services",
    "year": "2026"
   },
   {
    "name": "Kyoorius Creative Awards",
    "detail": "First List, Film Craft & Use of Technology/AI",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Gold, Most Disruptive Creative & Design Team (Razorpay)",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Silver, Most Disruptive B2B Campaign",
    "year": "2026"
   }
  ]
 },
 "contact": {
  "headline": "Let's make something *people talk about.*",
  "email": "onlyvibhor@gmail.com",
  "links": [
   {
    "label": "Behance",
    "url": "https://www.behance.net/onlyvibhor"
   },
   {
    "label": "LinkedIn",
    "url": "https://www.linkedin.com/in/onlyvibhor/"
   },
   {
    "label": "Instagram",
    "url": "https://www.instagram.com/onlyvibhor/"
   },
   {
    "label": "ADPList",
    "url": "https://adplist.org/mentors/vibhor-mathur"
   }
  ]
 }
};
window.ABOUT = {
 "meta": {
  "title": "About — Vibhor Mathur",
  "description": "Self-taught designer from Jaipur, engineer by degree. Communication Design Senior Manager at Razorpay, formerly Associate Director at Grofers. Also an artist working with AI, stop motion and found objects."
 },
 "label": "About",
 "headline": "Designing narratives by day. Crafting emotions through *art* by night.",
 "portrait": "assets/img/profile.png",
 "portrait_caption": "Jaipur → Bengaluru",
 "facts": [
  {
   "label": "Currently",
   "value": "Communication Design Senior Manager, Razorpay"
  },
  {
   "label": "Based",
   "value": "Bengaluru, India. Roots in Jaipur."
  },
  {
   "label": "Education",
   "value": "B.Tech, Computer Engineering. Government Engineering College Bikaner, 2010 to 2014."
  },
  {
   "label": "Languages",
   "value": "English, Hindi"
  }
 ],
 "numbers": [
  {
   "value": "11",
   "label": "years in consumer commerce and fintech, since March 2015"
  },
  {
   "value": "10+",
   "label": "product lines and business units on one deck design language"
  },
  {
   "value": "4",
   "label": "AI production tools built in-house and used on live campaigns"
  }
 ],
 "intro": [
  "I'm a self-taught designer from Jaipur with a degree in computer engineering. By day I make advertising and brand narratives. Outside the office I make art, mostly by turning everyday objects into small vessels of emotion and meaning.",
  "At Grofers, which became Blinkit, I spent over six years in marketing design: integrated campaigns around the app's recurring sale events, social content, app visual identities, and the hiring and development of a creative team. I left as Associate Director in October 2021.",
  "Since then I've led Communication Design at Razorpay across Payments, RazorpayX and POS. The work is brand films, keynote videos, landing pages, sales decks, social campaigns and product imagery, held together by one visual system and a way of telling stories that starts from data, consumer interviews and what past campaigns taught us.",
  "A lot of that work is now AI-native. *Trial of the Century*, the animal-courtroom film for RazorpayX Payroll, won Generative AI at the Shorty Awards. *Break To Build* turned one photograph of each of thirty founders into thirty ad films. Both ran as repeatable production systems rather than one-offs, and the design team now uses four in-house AI tools on live campaigns."
 ],
 "timeline": {
  "label": "Path",
  "items": [
   {
    "years": "Oct 2021 — Now",
    "org": "Razorpay",
    "role": "Communication Design Senior Manager · Bengaluru",
    "note": "Leads Communication Design across Payments, RazorpayX and POS: brand films, keynote videos, landing pages, sales decks, social campaigns and product imagery. Established a deck design language now used across more than ten product lines and business units."
   },
   {
    "years": "Mar 2015 — Oct 2021",
    "org": "Grofers (now Blinkit)",
    "role": "Associate Director, Marketing Design · Gurugram",
    "note": "Integrated advertising for recurring sale events, social campaigns and app visual identities. Hired and developed the creative team and directed external production partners."
   },
   {
    "years": "2010 — 2014",
    "org": "Government Engineering College Bikaner",
    "role": "B.Tech, Computer Engineering",
    "note": "Design was already happening alongside the degree: a CopyPress Infographic Designer certificate followed in December 2013."
   }
  ]
 },
 "leadership": {
  "label": "On creative leadership",
  "title": "Notes from running an in-house design team.",
  "intro": "From a 2024 post on planning the year for in-house design teams. The ideas I still work from:",
  "items": [
   {
    "title": "Keep widening the toolkit",
    "body": "Video and animation, 3D in Blender and Spline, and AI tools such as ChatGPT, Midjourney, Ideogram and Runway. Continuous learning keeps a team competitive, and engaged."
   },
   {
    "title": "Make goals measurable",
    "body": "Use analytics not only to validate creative work but to show how it contributes to the company. Aim for content that resonates, from social buzz to booklets that win over the most numbers-minded colleague."
   },
   {
    "title": "Build a culture that can take risks",
    "body": "Turn brainstorms from dreaded meetings into hubs of collaboration, where trying something bold does not mean fearing failure."
   },
   {
    "title": "Design for the business, not just the brief",
    "body": "Work in step with the brand marketing team so the output reflects company goals, not only creative ambition."
   }
  ],
  "source": {
   "label": "Read the original post",
   "url": "https://www.onlyvibhor.com/post/setting-up-design-lead-goals-for-2025"
  }
 },
 "studio": {
  "label": "After hours",
  "title": "The studio at night.",
  "body": "In my creative studio I work on AI art, stop-motion animation and found-object art, and make fun, quirky content for platforms, especially Instagram. The work runs from introspective musings to whimsical one-liners.\n\nTwo AI experiments from 2023, built on Stable Diffusion and ControlNet, live in the Lab.",
  "link": {
   "label": "Open the Lab",
   "url": "lab.html"
  }
 },
 "teaching": {
  "label": "Teaching and mentoring",
  "items": [
   {
    "name": "ADPList",
    "detail": "Design mentor. 60-minute one-to-one mentorship sessions."
   },
   {
    "name": "GrowthSchool",
    "detail": "Mentor."
   },
   {
    "name": "AI in art and design workshop",
    "detail": "Image generation, AI video and AI-assisted UI design, March 2024."
   },
   {
    "name": "AI design workshops",
    "detail": "Whole Truth Foods, Wolfkrafft."
   },
   {
    "name": "JK Lakshmipat University, Jaipur",
    "detail": "Short course on generative AI design."
   },
   {
    "name": "Conversations",
    "detail": "Designland, Groundbreakin Podcast, Design Tank, xtended Pack Collective."
   }
  ],
  "quote": {
   "text": "He felt more like an elder brother than just a mentor.",
   "who": "Vibhu Kapil, visual and motion designer, on ADPList"
  },
  "link": {
   "label": "See all mentorship, workshops and talks",
   "url": "mentorship.html"
  }
 },
 "recognition": {
  "label": "Recognition",
  "items": [
   {
    "name": "Shorty Awards",
    "detail": "Winner, Generative AI. Gold Honor, Financial Services. Finalist, Community Engagement.",
    "work": "Trial of the Century",
    "year": "2026"
   },
   {
    "name": "Kyoorius Creative Awards",
    "detail": "First List: Film Craft; Use of Technology & AI.",
    "work": "Trial of the Century",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Gold, Most Disruptive Creative & Design Team.",
    "work": "Razorpay",
    "year": "2026"
   },
   {
    "name": "ET Brand Disruption Awards",
    "detail": "Silver, Most Disruptive B2B Campaign.",
    "work": "Trial of the Century",
    "year": "2026"
   }
  ]
 },
 "writing": {
  "label": "Writing",
  "items": [
   {
    "title": "Embracing Creative Leadership in 2025: Strategies for In-House Design Teams",
    "date": "Apr 2024",
    "url": "https://www.onlyvibhor.com/post/setting-up-design-lead-goals-for-2025"
   },
   {
    "title": "Navigating the Frontier of Creativity: The Potential of AI in Art and Design",
    "date": "Mar 2024",
    "url": "https://www.onlyvibhor.com/post/navigating-the-frontier-of-creativity-unveiling-the-potential-of-ai-in-art-and-design"
   },
   {
    "title": "Habitats without the life",
    "date": "Dec 2023",
    "url": "https://www.onlyvibhor.com/post/habitats-without-the-life"
   },
   {
    "title": "Stable Diffusion AI and ControlNet",
    "date": "Nov 2023",
    "url": "https://www.onlyvibhor.com/post/stable-diffusion-ai-and-controlnet"
   }
  ]
 },
 "elsewhere": {
  "label": "Elsewhere",
  "items": [
   {
    "label": "Behance",
    "url": "https://www.behance.net/onlyvibhor"
   },
   {
    "label": "LinkedIn",
    "url": "https://www.linkedin.com/in/onlyvibhor/"
   },
   {
    "label": "Instagram",
    "url": "https://www.instagram.com/onlyvibhor/"
   },
   {
    "label": "YouTube",
    "url": "https://www.youtube.com/channel/UCYz6bkPGCR3gapGpoDKuSDg"
   },
   {
    "label": "X",
    "url": "https://twitter.com/onlyvibhor"
   },
   {
    "label": "ADPList",
    "url": "https://adplist.org/mentors/vibhor-mathur"
   }
  ]
 }
};
window.MENTORSHIP = {
 "meta": {
  "title": "Mentorship — Vibhor Mathur",
  "description": "One-to-one design mentoring on ADPList, plus workshops, talks and conversations on AI in design, from Vibhor Mathur, Communication Design Senior Manager at Razorpay."
 },
 "label": "Mentorship",
 "headline": "Sharing what I've learned, one *designer* at a time.",
 "intro": "Alongside leading a design team, I mentor designers one to one, teach workshops on AI in design, and join panels and conversations about the craft. This page collects all of it, and how to book me.",
 "teaser": {
  "label": "Mentorship",
  "title": "Mentoring designers, one conversation at a time.",
  "body": "One-to-one sessions on ADPList, workshops on AI in design, talks and podcasts.",
  "cta": "See all mentorship"
 },
 "numbers": [
  {
   "value": "33",
   "label": "one-to-one sessions completed on ADPList"
  },
  {
   "value": "31",
   "label": "hours of mentoring time, 1,860 minutes"
  },
  {
   "value": "60",
   "label": "minutes per session, one to one"
  }
 ],
 "numbers_note": "As listed on my ADPList profile.",
 "oneonone": {
  "label": "One to one",
  "title": "Mentoring on ADPList.",
  "body": "I'm a design mentor on ADPList, offering 60-minute one-to-one mentorship sessions. Sessions are one to one and shaped around what each mentee needs. Mentees have come for feedback on their design approach, for a clearer picture of what is expected of a designer, and for help figuring out where to push next.",
  "topics_label": "What we can talk about",
  "topics": [
   "Design",
   "Marketing",
   "Graphic design",
   "Motion design",
   "Branding and identity",
   "Design communication",
   "Critical thinking",
   "Presentation skills",
   "Leadership",
   "Video editing"
  ],
  "cta": {
   "label": "Book a session on ADPList",
   "href": "https://adplist.org/mentors/vibhor-mathur"
  }
 },
 "voices": {
  "label": "What mentees say",
  "note": "Reviews from my ADPList profile.",
  "items": [
   {
    "text": "He felt more like an elder brother than just a mentor, offering helpful lessons that were based on his journey.",
    "who": "Vibhu Kapil, visual and motion designer"
   },
   {
    "text": "His extensive experience and expertise in communication design shone through during our session. He offered invaluable insights and feedback.",
    "who": "ADPList mentee"
   },
   {
    "text": "My session with Vibhor was an eye-opener. He helped me understand the expectations for a designer and how to embark on that journey.",
    "who": "ADPList mentee"
   }
  ]
 },
 "events": {
  "label": "Talks and workshops",
  "title": "Teaching what the studio is learning.",
  "body": "The sessions draw on running an in-house design team: how AI changes the workflow, and what designers can learn next.",
  "items": [
   {
    "title": "Revolutionizing Design Workflows with AI: Razorpay's Success Story",
    "host": "GrowthSchool",
    "type": "Webinar",
    "date": "9 Sept 2023",
    "detail": "A 90-minute free session on how Razorpay's design team uses AI.",
    "image": "assets/img/mentor/growthschool.jpg"
   },
   {
    "title": "Revolutionizing Design Workflows with AI",
    "host": "Designland",
    "type": "Virtual session",
    "date": "27 April 2024",
    "detail": "A one-hour free virtual session for the Designland community.",
    "image": "assets/img/mentor/designland.jpg"
   },
   {
    "title": "AI in Design: A Silent Revolution",
    "host": "xtended Pack Collective",
    "type": "Workshop",
    "date": "",
    "detail": "Exploring the future design world with the power of AI.",
    "image": "assets/img/mentor/extended.jpg"
   },
   {
    "title": "Design Tank, Season 2",
    "host": "Design Tank",
    "type": "Mentor",
    "date": "",
    "detail": "Portfolio feedback and mentorship alongside Fatema Raja and Amit Patel.",
    "image": "assets/img/mentor/designtank.jpg"
   },
   {
    "title": "The Groundbreakin Podcast, episode 046",
    "host": "Groundbreakin",
    "type": "Podcast",
    "date": "",
    "detail": "A podcast conversation about design.",
    "image": "assets/img/mentor/groundbreakin.jpg"
   },
   {
    "title": "AI in art and design",
    "host": "Workshop",
    "type": "Workshop",
    "date": "March 2024",
    "detail": "Image generation, AI video and AI-assisted UI design.",
    "image": ""
   },
   {
    "title": "AI design workshops for teams",
    "host": "Whole Truth Foods, Wolfkrafft",
    "type": "In-house workshops",
    "date": "",
    "detail": "AI design workshops for Whole Truth Foods and Wolfkrafft.",
    "image": ""
   },
   {
    "title": "Generative AI design",
    "host": "JK Lakshmipat University, Jaipur",
    "type": "Short course",
    "date": "",
    "detail": "A short course on generative AI design.",
    "image": ""
   }
  ]
 },
 "gallery": {
  "label": "In the room",
  "items": [
   {
    "image": "assets/img/mentor/photo.jpg",
    "caption": "Presenting at a workshop",
    "tall": true
   },
   {
    "image": "assets/img/mentor/room.jpg",
    "caption": "On a panel"
   },
   {
    "image": "assets/img/mentor/podcast.jpg",
    "caption": "Recording a podcast"
   },
   {
    "image": "assets/img/mentor/stream.jpg",
    "caption": "A live conversation with Sanjay Reddy"
   }
  ]
 },
 "reading": {
  "label": "Further reading",
  "items": [
   {
    "title": "Navigating the Frontier of Creativity: The Potential of AI in Art and Design",
    "date": "Mar 2024",
    "url": "https://www.onlyvibhor.com/post/navigating-the-frontier-of-creativity-unveiling-the-potential-of-ai-in-art-and-design"
   },
   {
    "title": "Embracing Creative Leadership in 2025: Strategies for In-House Design Teams",
    "date": "Apr 2024",
    "url": "https://www.onlyvibhor.com/post/setting-up-design-lead-goals-for-2025"
   }
  ]
 },
 "cta": {
  "label": "Work with me",
  "title": "Want a session, a workshop or a talk?",
  "body": "Book a one-to-one on ADPList, or email me about a workshop for your team or community.",
  "buttons": [
   {
    "label": "Book on ADPList",
    "href": "https://adplist.org/mentors/vibhor-mathur"
   },
   {
    "label": "Email about a workshop",
    "href": "mailto:onlyvibhor@gmail.com?subject=Workshop%20or%20talk"
   }
  ]
 }
};
window.TOOLKIT = {
 "meta": {
  "title": "AI Toolkit — Vibhor Mathur",
  "description": "How the Razorpay design team uses AI to build its own tools: automating set tasks, scaling production, teaching beginners and shipping interactive web campaigns without waiting for a developer."
 },
 "label": "AI Toolkit",
 "headline": "Tools that make the *work*, built by the people who make the work.",
 "intro": "AI is not only a way to make images. Used properly, it lets a design team build its own software: tools for the studio, tools for marketing, and interactive web experiences that designers ship themselves. This is that toolkit, and what it changed.",
 "principles": [
  {
   "title": "Prompts are inputs",
   "body": "A prompt is one ingredient, not the product. The product is what you wrap around it."
  },
  {
   "title": "Tools are modules",
   "body": "Small tools with a single job, each with a proper interface, that can be combined and reused."
  },
  {
   "title": "Systems create consistency",
   "body": "Brand, lighting, faces and scenes are held in the tool, so the hundredth output looks like the first."
  }
 ],
 "pillars": [
  {
   "title": "Automate the set tasks",
   "body": "Work that repeats, such as turning one founder photo into a campaign library or one product shot into a scene, stops being a design request and becomes a button. The designers' time goes to the idea and the finish.",
   "proof": [
    {
     "label": "Founder Image Generator",
     "detail": "One photo in, a full campaign library out. 4K, one click."
    },
    {
     "label": "Social Content Gen",
     "detail": "A founder photo and a business story in, a composed, campaign-ready post out."
    }
   ]
  },
  {
   "title": "Scale up production",
   "body": "When the tool holds the look, volume stops costing quality. The same pipeline that produced 81 television films for 20 founders also produced a newspaper front page and more than 200 social posts, with no cameras, sets or lights.",
   "proof": [
    {
     "label": "Backing India's Start-Up Champions",
     "detail": "81 films, 1 newspaper ad, 200+ social posts.",
     "href": "case.html?c=t20"
    },
    {
     "label": "Razorbae, AI avatar",
     "detail": "Shot once, trained into a system: 129 reels and 6.55 million views."
    }
   ]
  },
  {
   "title": "Easy to learn, even for beginners",
   "body": "A blank prompt box is intimidating. A panel with lenses, lighting, presets and references is not. Wrapping models in clear interfaces gives a beginner a good starting point on day one, and gives the whole team one shared way of working.",
   "proof": [
    {
     "label": "Interfaces, not prompts",
     "detail": "Every tool is built with an interface in Gemini Studio, so the controls are visible and the learning curve is short."
    },
    {
     "label": "Workshops and mentoring",
     "detail": "AI design workshops, talks and one-to-one mentoring for designers starting out."
    }
   ]
  },
  {
   "title": "Designers shipping interactive web, themselves",
   "body": "Campaign sites, landing pages and playable games used to wait in a developer queue. With AI-assisted building, designers take an idea from sketch to a live interactive page, and own the motion, the feel and the details end to end.",
   "proof": [
    {
     "label": "Magic Checkout landing page",
     "detail": "An immersive scroll-through world with micro-animations.",
     "href": "case.html?c=magic-checkout"
    },
    {
     "label": "Back in the Ring",
     "detail": "A parallax landing page and a playable game.",
     "href": "case.html?c=ring"
    }
   ]
  }
 ],
 "tools_head": {
  "label": "The studio's tools",
  "title": "Built in-house. Used on live campaigns.",
  "body": "Each one started as a repeating task on a real campaign, and became a tool the whole team could pick up."
 },
 "tools": [
  {
   "name": "Cinematography Tool",
   "tag": "For film and ads",
   "body": "A virtual camera department. Pick the lens, set the light, choose the grade, and the scene follows.",
   "bullets": [
    "20+ camera lens simulations",
    "Advanced lighting control",
    "100+ colour grading variations"
   ],
   "built_with": "Gemini Studio for the interface, Nano Banana API",
   "hero": "assets/img/tools/cine-ui.jpg",
   "gallery": [
    "assets/img/tools/cine-1.jpg",
    "assets/img/tools/cine-2.jpg",
    "assets/img/tools/cine-4.jpg",
    "assets/img/tools/cine-5.jpg"
   ]
  },
  {
   "name": "Product Image Generator",
   "tag": "For product marketing",
   "body": "Virtual product photography that keeps the brand together. Drop in a product and get it placed in an environment, lit and composed.",
   "bullets": [
    "Infinite variations",
    "Consistent brand visuals",
    "No physical shoots required"
   ],
   "built_with": "Gemini Studio for the interface, Nano Banana API",
   "hero": "assets/img/tools/prod-ui.jpg",
   "gallery": [
    "assets/img/tools/prod-1.jpg",
    "assets/img/tools/prod-4.jpg",
    "assets/img/tools/prod-5.jpg",
    "assets/img/tools/prod-7.jpg"
   ]
  },
  {
   "name": "Advanced Image Editor",
   "tag": "For continuity",
   "body": "One scene, many angles, the same faces. Built for the moments where a single hero image is not enough and consistency is the whole job.",
   "bullets": [
    "A consistent scene from different angles",
    "Continuity frames",
    "Multi-reference generation: scene, style, lighting, colour and face"
   ],
   "built_with": "Gemini Studio for the interface, Nano Banana API",
   "hero": "assets/img/tools/edit-ui.jpg",
   "gallery": [
    "assets/img/tools/edit-2.jpg",
    "assets/img/tools/edit-3.jpg",
    "assets/img/tools/edit-4.jpg",
    "assets/img/tools/edit-5.jpg"
   ]
  },
  {
   "name": "Founder Image Generator",
   "tag": "For campaigns with people",
   "body": "Converts one founder image into multiple visuals across clothing, pose and lighting. It was the engine behind the T20 campaign.",
   "bullets": [
    "Transformations across clothing, pose and lighting",
    "4K generation in one click",
    "20+ founders from a single source photo each"
   ],
   "built_with": "Gemini, Nano Banana API",
   "hero": "assets/img/tools/founder-ui.jpg",
   "gallery": [
    "assets/img/tools/founder-grid.jpg",
    "assets/img/tools/founder-panel.jpg",
    "assets/img/tools/founder-1.jpg",
    "assets/img/tools/founder-2.jpg"
   ]
  },
  {
   "name": "Social Content Gen",
   "tag": "For high volume",
   "body": "A high-volume, personalised post creator. Give it a founder image and a business success story; preset combinations of clothing, pose, lighting and background do the rest.",
   "bullets": [
    "Input: a founder image and a business story",
    "Preset clothing, pose, lighting and background",
    "Fully composed, campaign-ready social posts"
   ],
   "built_with": "Replit, Gemini, ChatGPT and Nano Banana",
   "hero": "assets/img/tools/social-flow.jpg",
   "gallery": [
    "assets/img/tools/social-1.jpg",
    "assets/img/tools/social-2.jpg",
    "assets/img/tools/social-3.jpg",
    "assets/img/tools/social-posts.jpg"
   ]
  }
 ],
 "interactive": {
  "label": "Interactive web",
  "title": "Pages you can play with, shipped by designers.",
  "body": "Beyond images and films, the team has had interactive web experiences built for campaigns: landing pages with scroll worlds, micro-animations and a playable game. They sit alongside the toolkit because they use the same idea: design owns the idea and the feel, and AI shortens the distance to something live.",
  "items": [
   {
    "title": "Magic Checkout",
    "tag": "Landing page",
    "body": "An immersive landing page where you experience what checkout does, from the magic you see to the science behind it.",
    "image": "assets/img/p/magic-cover.jpg",
    "href": "case.html?c=magic-checkout"
   },
   {
    "title": "Back in the Ring",
    "tag": "Landing page and game",
    "body": "A parallax landing page that pulls you into the ring, plus a game where each opponent defeated unlocks a new feature.",
    "image": "assets/img/p/ring-cover.jpg",
    "href": "case.html?c=ring"
   },
   {
    "title": "The Wall of Laughter",
    "tag": "Interactive board",
    "body": "An anonymous digital board where HR professionals shared the funniest salary questions they had ever received.",
    "image": "assets/img/p/trial-1.jpg",
    "href": "https://razorpayxwalloflaughter.razorpay.com/"
   },
   {
    "title": "Backing India's Boldest",
    "tag": "Landing page and social",
    "body": "Glambot-style camera motion videos of founders for a landing page and social content, built around character realism and cinematic slow motion.",
    "image": "",
    "href": ""
   }
  ]
 },
 "learn": {
  "label": "Learning",
  "title": "The tools are only half of it. The team has to be able to use them.",
  "body": "Beginners are the point. The toolkit is taught, not just handed over: through workshops, talks and mentoring that start from what AI can do for a designer.",
  "items": [
   {
    "name": "Revolutionizing Design Workflows with AI",
    "detail": "Designland workshop."
   },
   {
    "name": "Revolutionizing Design Workflows with AI: Razorpay's Success Story",
    "detail": "GrowthSchool."
   },
   {
    "name": "AI in Design: A Silent Revolution",
    "detail": "xtended Pack Collective workshop."
   },
   {
    "name": "Design Tank",
    "detail": "Feedback and mentorship from top design leaders."
   },
   {
    "name": "Groundbreakin Podcast",
    "detail": "Podcast conversation."
   }
  ],
  "images": [
   {
    "image": "assets/img/tools/talk-designland.jpg",
    "caption": "Designland"
   },
   {
    "image": "assets/img/tools/talk-growthschool.jpg",
    "caption": "GrowthSchool"
   },
   {
    "image": "assets/img/tools/talk-extended.jpg",
    "caption": "xtended Pack Collective"
   },
   {
    "image": "assets/img/tools/talk-designtank.jpg",
    "caption": "Design Tank"
   }
  ],
  "wide": "assets/img/tools/talk-room.jpg",
  "link": {
   "label": "More on mentoring and workshops",
   "href": "mentorship.html"
  }
 },
 "stack": {
  "label": "The stack",
  "items": [
   "Midjourney",
   "Nano Banana API",
   "ChatGPT",
   "Claude",
   "Gemini",
   "Topaz Labs",
   "Suno AI",
   "Adobe Firefly",
   "Replit",
   "Kling",
   "RunwayML",
   "ElevenLabs",
   "Veo 2"
  ]
 },
 "team": {
  "label": "With the team",
  "body": "The tools were built and used with the Razorpay communication design team, including communication designers Aadithya Narayanan, Jasleen Kaur and Pyukil Janwani."
 },
 "cta": {
  "label": "See the work these tools made",
  "href": "work.html"
 }
};
window.PROJECTS = [
 {
  "title": "Trial of the Century",
  "slug": "trial",
  "published": true,
  "featured": true,
  "order": 1,
  "title_lines": "Trial of the\nCentury",
  "card_title": "Trial of the\nCentury",
  "client": "RazorpayX Payroll",
  "year": "2025",
  "category": "AI film · Campaign",
  "role": "Art Direction",
  "tagline": "An animal courtroom puts HR's most dreaded monthly question on trial.",
  "summary": "A Panchatantra-style courtroom film that turned payslip confusion into a pop-culture moment for the HR community.",
  "cover": {
   "image": "assets/img/p/trial-1.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "2.1M+",
    "label": "impressions"
   },
   {
    "value": "1.5M+",
    "label": "unique accounts reached"
   },
   {
    "value": "8.64%",
    "label": "engagement rate, 4× the B2B fintech average"
   },
   {
    "value": "13%",
    "label": "uplift in leads during the campaign"
   },
   {
    "value": "16%",
    "label": "surge in website traffic"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Reach the HR community, a relevant audience that is notoriously hard to engage.",
    "body": "RazorpayX Payroll needed awareness among HR professionals. They are the right audience, but a finance-heavy product is a tough sell to people who rarely engage with branded content.\n\nA recent launch gave us a way in: an AI feature that lets employees talk directly to their payslips and ask salary questions. HRs showed genuine traction, which made us dig deeper into why."
   },
   {
    "type": "statement",
    "text": "For employees, Salary Day is the most anticipated day of the month. For HR, it is a week-long nightmare."
   },
   {
    "type": "text",
    "label": "The insight",
    "title": "The same questions, every month, and everyone had accepted it.",
    "body": "The moment salaries hit accounts, inboxes flood: *Why did my salary change? What is this deduction?* Not out of carelessness, but because payslips are dense with abbreviations, tax codes and compliance jargon that few people understand.\n\nOver time the dependency became normal. HRs absorbed it, employees assumed it. **That cultural resignation became our creative brief.**"
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-1.jpg",
    "caption": "Campaign overview: insight, design brief, idea and results",
    "size": "full"
   },
   {
    "type": "text",
    "label": "The idea",
    "title": "If the same questions come back every month, the system needs fixing, not the people.",
    "body": "We reframed repeated salary queries as a payroll design flaw and put the repetition on trial, in an animal courtroom inspired by the Panchatantra and an unmistakable piece of Hindi cinema, the *sawaal pe sawaal* courtroom scene from *Damini*.\n\n- **Porcumar Rao**, a porcupine, takes every recurring query like a spoke in his back.\n- **Chulbull Pandey**, the aggressive bull, channels the courtroom cross-examination.\n- **Hathiram Trankalp**, a wise elephant, presides over the chaos.\n- **The employees** appear as a flock of chirping birds.\n\nWithin the story, RazorpayX Payroll introduces R.A.Y., an AI assistant that reads the payslip and explains any change instantly, in simple language, without HR stepping in."
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-3.jpg",
    "caption": "Location design and character sheets",
    "size": "full"
   },
   {
    "type": "steps",
    "label": "The process",
    "title": "Animation-quality world-building without a single traditional animation tool.",
    "items": [
     {
      "title": "Explore",
      "body": "Character and mood explorations, iterated until the tone and personalities felt right.",
      "tools": "Midjourney"
     },
     {
      "title": "Lock the world",
      "body": "A digital map of the courtroom with every camera position fixed before a frame was generated: spatial logic instead of prompt randomness.",
      "tools": "Midjourney · Gemini · ChatGPT"
     },
     {
      "title": "Frame",
      "body": "Camera and framing prompts written with ChatGPT and Gemini, then executed through Nano Banana for consistent multi-angle shots, refined for continuity and texture.",
      "tools": "Nano Banana · Photoshop · Firefly"
     },
     {
      "title": "Animate",
      "body": "Performances generated and iterated until body language and facial expression felt natural.",
      "tools": "Kling · Runway · Google Veo"
     },
     {
      "title": "Voice",
      "body": "Professional voice actors chosen to embody each character, with lip-sync aligned to the recorded performance.",
      "tools": "Kling Lip Sync · ElevenLabs"
     },
     {
      "title": "Finish",
      "body": "Composited, edited and upscaled to 4K at 60fps.",
      "tools": "After Effects · Premiere · Topaz Labs"
     }
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-2.jpg",
    "caption": "The production workflow, from moodboard to final edit",
    "size": "wide"
   },
   {
    "type": "image",
    "image": "assets/img/p/trial-4.jpg",
    "caption": "Animation, expression and voice direction",
    "size": "wide"
   },
   {
    "type": "video",
    "url": "https://www.youtube.com/watch?v=uDeZ0zKgVqY",
    "poster": "",
    "caption": "The film",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Beyond the film",
    "title": "We gave HRs a place to be heard, and a soundtrack.",
    "body": "**The Wall of Laughter** was an anonymous digital board where HR professionals shared the funniest salary questions they had ever received. Anonymity mattered: HR professionals are cautious about being seen online, so humour became a safe way in.\n\n**\"Inbox Avalanche\"**, a debut music single, turned the monthly flood into a hook and earned 4.5 lakh+ impressions and 50+ saves. B2B content, competing with entertainment.\n\nThe movement spread through HR communities across India, including The Shape of Work, People Matters, SHRM India, Being HR and HR Breakfast Club."
   },
   {
    "type": "metrics",
    "label": "The result",
    "items": [
     {
      "value": "2.1M+",
      "label": "impressions"
     },
     {
      "value": "135K+",
      "label": "total engagements at an 8.64% rate"
     },
     {
      "value": "300K",
      "label": "HR professionals reached, of a 650K online audience"
     },
     {
      "value": "300+",
      "label": "brand mentions"
     },
     {
      "value": "250+",
      "label": "reposts"
     },
     {
      "value": "13%",
      "label": "uplift in D&O leads"
     }
    ]
   },
   {
    "type": "text",
    "label": "The takeaway",
    "title": "The narrative shifted from \"HR failure\" to \"systemic gap\".",
    "body": "What began as a feature launch turned into a pop-culture moment inside the HR ecosystem, with startups across the space (Plum, Spring Verify, ClearTax, Smartstaff, Jify, Fi) engaging with a campaign that, for once, was about HR."
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Art Director"
   },
   {
    "name": "Sourajit Sengupta",
    "role": "Creative Director"
   },
   {
    "name": "Saurabh Soni",
    "role": "Vice President, Design"
   },
   {
    "name": "Apuarv Sethi",
    "role": "Vice President, Marketing"
   },
   {
    "name": "Subhash Dawda",
    "role": "Marketing, RazorpayX"
   },
   {
    "name": "Priyank Hegde",
    "role": "Design"
   },
   {
    "name": "Rahul Girish",
    "role": "Design"
   },
   {
    "name": "Aadithya Narayanan S",
    "role": "Design"
   },
   {
    "name": "Siddhant Tiwari",
    "role": "Design"
   },
   {
    "name": "Othneil Dutta",
    "role": "Design"
   },
   {
    "name": "Nihar Gopal Lohiya",
    "role": "Marketing"
   },
   {
    "name": "Nikita Pinto",
    "role": "Marketing"
   },
   {
    "name": "Sushmit Sengupta",
    "role": "Marketing"
   },
   {
    "name": "Nivedita Prabhu",
    "role": "Marketing"
   },
   {
    "name": "Gurnain Kaur Gopal Singh Thapar",
    "role": "Marketing"
   },
   {
    "name": "Gurunicketan S",
    "role": "Content"
   }
  ],
  "awards": [
   {
    "title": "Shorty Awards",
    "detail": "Winner, Generative AI"
   },
   {
    "title": "Shorty Awards",
    "detail": "Gold Honor, Financial Services"
   },
   {
    "title": "Shorty Awards",
    "detail": "Finalist, Community Engagement"
   },
   {
    "title": "Kyoorius Creative Awards 2026",
    "detail": "First List: Film Craft; Use of Technology & AI"
   },
   {
    "title": "ET Brand Disruption Awards 2026",
    "detail": "Silver, Most Disruptive B2B Campaign"
   }
  ],
  "links": [
   {
    "label": "Watch the film",
    "url": "https://www.youtube.com/watch?v=uDeZ0zKgVqY"
   },
   {
    "label": "Shorty Awards entry",
    "url": "https://shortyawards.com/18th/razorpayx-trial-of-the-century"
   },
   {
    "label": "Kyoorius listing",
    "url": "https://winners.kyoorius.com/winners/2026/kca/13684-trial-of-the-century/"
   },
   {
    "label": "Wall of Laughter",
    "url": "https://razorpayxwalloflaughter.razorpay.com/"
   },
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254333269/Trial-of-the-century"
   }
  ],
  "categories": [
   "AI Film",
   "Campaign"
  ]
 },
 {
  "title": "Break To Build",
  "slug": "btb",
  "published": true,
  "featured": true,
  "order": 2,
  "title_lines": "Break\nTo Build",
  "card_title": "Break\nTo Build",
  "client": "Razorpay × JioHotstar",
  "year": "2026",
  "category": "AI film · IPL campaign",
  "role": "Art & Creative Direction",
  "tagline": "Thirty founders. Thirty ad films. Zero shoots.",
  "summary": "A 100% AI experiment in making a TVC: founders photographed once, then broken, bent and built into cinematic films.",
  "cover": {
   "image": "assets/img/p/btb-1.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "30",
    "label": "AI-led ad films"
   },
   {
    "value": "30",
    "label": "founders featured"
   },
   {
    "value": "1",
    "label": "photograph per founder"
   },
   {
    "value": "0",
    "label": "live-action shoots"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Back the founders building India, on the biggest stage in Indian marketing.",
    "body": "Razorpay's IPL 2026 push on JioHotstar. The ambition was to match the scale and spectacle of the tournament, while also stress-testing everything the design team had learned about AI workflows, tooling and design systems over the year."
   },
   {
    "type": "statement",
    "text": "A 100% AI experiment in making a TVC. No actors. No stunts. No live-action shots."
   },
   {
    "type": "image",
    "image": "assets/img/p/btb-1.jpg",
    "caption": "Break To Build, Razorpay 2026",
    "size": "full"
   },
   {
    "type": "text",
    "label": "The launch film",
    "title": "What if breaking through was literal?",
    "body": "We took the campaign idea of breaking through and turned it into a visual statement: breaking, bending and defying the impossible."
   },
   {
    "type": "text",
    "label": "The problem",
    "title": "Getting 30 busy founders in one frame? Almost impossible.",
    "body": "A shoot at this scale means complex schedules and a massive production budget. Breaking glass, breaking walls, breaking ceilings means high-risk shots, high production costs, and founders who are not actors.\n\n**AI made it possible. Thirty founders. One frame. Zero logistics.**"
   },
   {
    "type": "image",
    "image": "assets/img/p/btb-4.jpg",
    "caption": "30 founders. 30 stories. One unusual production.",
    "size": "wide"
   },
   {
    "type": "steps",
    "label": "From a photoshoot to a TV commercial",
    "title": "One shoot and AI. Infinite possibilities.",
    "items": [
     {
      "title": "Shoot",
      "body": "Founders photographed once across carefully planned angles and poses."
     },
     {
      "title": "Style frames",
      "body": "We designed the visual language and built the worlds each founder would break through."
     },
     {
      "title": "Generate",
      "body": "AI transformed stills into cinematic environments, action and destruction."
     },
     {
      "title": "Craft",
      "body": "Shots were refined, composited and edited into finished films."
     }
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/btb-9.jpg",
    "caption": "From internal shoot, to planned poses, to worlds, to finished films",
    "size": "narrow"
   },
   {
    "type": "text",
    "label": "The takeaway",
    "title": "A stress test for everything the team had learned about AI.",
    "body": "Thirty ad films, a launch film, teasers, music and supporting content, produced AI-led from end to end: not AI-assisted, not AI-enhanced. It took collective conviction to say yes to something with no established playbook, on one of the biggest stages in Indian marketing."
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Art & Creative Direction"
   },
   {
    "name": "Rahul Girish",
    "role": "Design"
   },
   {
    "name": "Sourajit Sengupta",
    "role": "Creative Director"
   },
   {
    "name": "Varun Thakar",
    "role": "Partner"
   },
   {
    "name": "Talented.Agency",
    "role": "Partner"
   },
   {
    "name": "Neil Dutta",
    "role": ""
   },
   {
    "name": "Akash Wadhwa",
    "role": ""
   },
   {
    "name": "Sanjana Shetty",
    "role": ""
   },
   {
    "name": "Ishan Gupta",
    "role": ""
   },
   {
    "name": "Aadithya Narayanan S",
    "role": ""
   },
   {
    "name": "Ajay R Nath",
    "role": ""
   },
   {
    "name": "Nivedita Prabhu",
    "role": ""
   },
   {
    "name": "Ajmal Roshan",
    "role": ""
   },
   {
    "name": "Aman Shetty",
    "role": ""
   },
   {
    "name": "Ashish Thawani",
    "role": ""
   },
   {
    "name": "MarkMedia",
    "role": "Partner"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254665051/Break-To-Build-Razorpay-IPL-Campaign"
   }
  ],
  "categories": [
   "AI Film",
   "Campaign"
  ]
 },
 {
  "title": "Backing India's Start-Up Champions",
  "slug": "t20",
  "published": true,
  "featured": true,
  "order": 3,
  "title_lines": "Start-Up\nChampions",
  "card_title": "Start-Up\nChampions",
  "client": "Razorpay × T20 World Cup",
  "year": "2026",
  "category": "Broadcast · Print · Social",
  "role": "Art Direction",
  "tagline": "India celebrates cricketers and founders equally. Only one gets a stadium. We built one for both.",
  "summary": "81 television films, a newspaper front page and 200+ social posts for 20 founders, with no cameras, sets or lights.",
  "cover": {
   "image": "assets/img/p/t20-1.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "81",
    "label": "television films"
   },
   {
    "value": "8.1M",
    "label": "unique viewers"
   },
   {
    "value": "133%",
    "label": "increase in purchase intent"
   },
   {
    "value": "200+",
    "label": "extended social posts"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The idea",
    "title": "Put founders on the screen cricket fans are already watching.",
    "body": "The T20 World Cup season is when the nation watches together. Razorpay set out to back its start-up champions where attention already was, treating founders the way the country treats cricketers: with a stadium, a jersey and a player card."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-1.jpg",
    "caption": "Backing India's Start-Up Champions",
    "size": "full"
   },
   {
    "type": "statement",
    "text": "Viewers didn't see an ad. They saw a founder who belonged on that screen."
   },
   {
    "type": "text",
    "label": "TV ads",
    "title": "Designed to look like the broadcast, not interrupt it.",
    "body": "**81 films. 20 match dates. Zero shoots.** Each founder was lit three ways, warm daylight, floodlit blue and night drama, matched to every match slot.\n\nEvery film mirrored cricket player-card aesthetics: centre-composed, sportsman poses, stadium environment."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-5.jpg",
    "caption": "Television: lower-thirds, player cards and three lighting environments",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "The pipeline",
    "title": "20 founders. One photo each. No shoots, no studios, no waiting.",
    "body": "A custom avatar tool, built on the Nano Banana API and Gemini AI Studio, took a single reference image and returned a full campaign visual library: sportsman poses, campaign costume, expressions tuned to each founder's personality. 4K output, one click.\n\nEvery founder walked into the campaign looking like they had always belonged on that stage."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-4.jpg",
    "caption": "The custom avatar generation tool",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Social",
    "title": "Every founder. Every platform. One pipeline.",
    "body": "200+ extended social posts carried the campaign forward, including founders who did not appear in the TV spots. Drop in a founder photo and their business story and the pipeline returns a fully composed, campaign-ready post: title layouts per personality, costume, pose, lighting and background, all handled.\n\nNo individual design sessions. No back and forth. Just output."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Gemini",
     "Nano Banana",
     "Replit",
     "ChatGPT",
     "Banner Bear"
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-6.jpg",
    "caption": "Social content generation",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Print",
    "title": "The nation reads the paper. We put founders on the front page.",
    "body": "The same pipeline that built the TV assets produced full-page newspaper ads: same founder, same costume, same campaign language, in the hands of the same audience the morning after the match."
   },
   {
    "type": "image",
    "image": "assets/img/p/t20-7.jpg",
    "caption": "Print: founders on the front page",
    "size": "wide"
   },
   {
    "type": "image_grid",
    "columns": 1,
    "images": [
     {
      "image": "assets/img/p/t20-3.jpg",
      "caption": "81 ad films, 1 newspaper ad, 200+ social posts. No cameras. No sets. No lights."
     },
     {
      "image": "assets/img/p/t20-2.jpg",
      "caption": "Results"
     }
    ]
   },
   {
    "type": "metrics",
    "label": "The result",
    "items": [
     {
      "value": "450K+",
      "label": "CTV impressions"
     },
     {
      "value": "8.1M",
      "label": "unique viewers"
     },
     {
      "value": "928K",
      "label": "LinkedIn impressions"
     },
     {
      "value": "133%",
      "label": "purchase intent up"
     }
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Art Direction"
   },
   {
    "name": "Razorpay Communication Design",
    "role": "Design"
   },
   {
    "name": "Razorpay Marketing",
    "role": "Marketing"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254656865/Backing-Indias-Start-Up-Champions-T20-Campaign"
   }
  ],
  "categories": [
   "AI Film",
   "Campaign",
   "Social",
   "Print"
  ]
 },
 {
  "title": "Back in the Ring",
  "slug": "ring",
  "published": true,
  "featured": true,
  "order": 4,
  "title_lines": "Back in\nthe Ring",
  "card_title": "Back in\nthe Ring",
  "client": "Razorpay Netbanking",
  "year": "2026",
  "category": "Film · Landing page · Game",
  "role": "Creative Direction",
  "tagline": "A fallen champion, written off by one-tap payments, gets its redemption arc.",
  "summary": "A boxing-film trailer, a parallax landing page and a playable game, built end to end in-house to relaunch Netbanking.",
  "cover": {
   "image": "assets/img/p/ring-cover.jpg",
   "video": ""
  },
  "metrics": [],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Bring Netbanking back into the conversation.",
    "body": "Netbanking had quietly powered online payments for decades. In the age of one-tap UPI and cards it felt like an old champion written off by everyone. The brief was to bring it back not as a legacy payment method, but as a trusted contender making its comeback."
   },
   {
    "type": "steps",
    "label": "Three pieces, one story",
    "title": "Don't just watch the comeback. Play it.",
    "items": [
     {
      "title": "The film",
      "body": "Netbanking in the gym, drilling new features into knockout punches, training every round toward one goal: champion status, reclaimed."
     },
     {
      "title": "The arena",
      "body": "An interactive one-page landing page that breaks down the new tech powering the comeback, with parallax scrolling that pulls you deeper into the ring, every feature landing like a fresh combo."
     },
     {
      "title": "The game",
      "body": "Clear level after level; each opponent defeated unlocks a new feature, until the championship belt is back where it belongs."
     }
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/ring-2.jpg",
    "caption": "100% AI-powered filmmaking",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Production",
    "title": "A cinematic, trailer-like experience rather than a conventional fintech film.",
    "body": "Every character was created with AI, from environments to every visual detail, combined with art direction and a visual language designed to match international cinematic standards: a bold, premium take on a Netbanking comeback."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Claude",
     "Higgsfield",
     "Runway",
     "Gemini",
     "OpenAI",
     "Adobe",
     "Suno"
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": ""
   },
   {
    "name": "Sourajit Sengupta",
    "role": ""
   },
   {
    "name": "Neil Dutta",
    "role": ""
   },
   {
    "name": "Rahul Girish",
    "role": ""
   },
   {
    "name": "Aastha Bhat",
    "role": ""
   },
   {
    "name": "Aadithya Narayanan S",
    "role": ""
   },
   {
    "name": "Jasleen Kaur",
    "role": ""
   },
   {
    "name": "Aditya Mohan Gupta",
    "role": ""
   },
   {
    "name": "Vidushi S.",
    "role": ""
   },
   {
    "name": "Varun Thakar",
    "role": ""
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254798253/Back-in-the-ring-Netbanking-Comeback-Razorpay"
   }
  ],
  "categories": [
   "AI Film",
   "Landing Page / Web",
   "Campaign"
  ]
 },
 {
  "published": true,
  "featured": true,
  "title": "Magic Checkout Landing Page",
  "order": 5,
  "title_lines": "Magic\nCheckout",
  "card_title": "Magic\nCheckout",
  "client": "Razorpay",
  "year": "2026",
  "category": "Landing page · Motion",
  "role": "Art Direction · Web Design",
  "tagline": "It's not just a checkout. It's engineered magic.",
  "summary": "An immersive landing page that lets visitors experience what Magic Checkout does, instead of reading a list of features.",
  "categories": [
   "Landing Page / Web",
   "Motion"
  ],
  "cover": {
   "image": "assets/img/p/magic-cover.jpg",
   "video": ""
  },
  "metrics": [],
  "sections": [
   {
    "type": "text",
    "label": "The idea",
    "title": "Don't explain checkout. Let people feel it.",
    "body": "The Razorpay Magic Checkout landing page turns a complex checkout technology into an immersive magical experience. Instead of simply explaining features, the page lets you experience what Magic Checkout does, making every step of checkout feel effortless and almost automatic."
   },
   {
    "type": "video",
    "url": "assets/vid/magic-02.mp4",
    "poster": "",
    "caption": "The hero: \"It's Not Just A Checkout. It's Engineered Magic.\"",
    "size": "wide",
    "loop": true
   },
   {
    "type": "image",
    "image": "assets/img/p/magic-page.jpg",
    "caption": "The landing page: the hero, the missing piece in D2C growth, and the first of four scenes",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "Four scenes",
    "title": "One product story, four ways in.",
    "body": "The page is organised around four stories a merchant cares about: **Boost Conversion**, **COD Control**, **Improve Purchase Intent** and **Build Loyalty**. Each plays out on a floating island with a mock storefront, so the product screens sit inside a world rather than on a slide."
   },
   {
    "type": "statement",
    "text": "Magic on the surface. Science underneath."
   },
   {
    "type": "text",
    "label": "Magic → Science",
    "title": "From the magic you see to the science behind it.",
    "body": "The experience shifts from an immersive magical world to a technical wireframe, revealing the data, logic and systems powering the seamless checkout experience."
   },
   {
    "type": "video",
    "url": "assets/vid/magic-07.mp4",
    "poster": "",
    "caption": "Signal-based nudges and gamified coupons, shown as the system behind the scene",
    "size": "wide",
    "loop": true
   },
   {
    "type": "text",
    "label": "Micro animations",
    "title": "Making every interaction *feel alive*.",
    "body": "A series of subtle micro-animations bring the interface and its features to life, adding moments of delight while making complex interactions feel intuitive and effortless."
   },
   {
    "type": "clips",
    "columns": 2,
    "clips": [
     {
      "video": "assets/vid/magic-11.mp4",
      "caption": "Add to cart, Buy Now"
     },
     {
      "video": "assets/vid/magic-12.mp4",
      "caption": "Coupons and payment offers"
     },
     {
      "video": "assets/vid/magic-14.mp4",
      "caption": "Payment options, cash on delivery"
     },
     {
      "video": "assets/vid/magic-15.mp4",
      "caption": "Saved offers and recommended methods"
     }
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": ""
   },
   {
    "name": "Rahul Girish",
    "role": ""
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/254362459/Magic-Checkout-Landing-Page"
   }
  ],
  "slug": "magic-checkout"
 },
 {
  "published": true,
  "featured": true,
  "title": "Agentic Commerce Engine Launch Video",
  "order": 6,
  "title_lines": "Agentic\nCommerce\nEngine",
  "card_title": "Agentic\nCommerce Engine",
  "client": "Razorpay · GFF 26",
  "year": "2026",
  "category": "AI film · Launch video",
  "role": "Art Direction",
  "tagline": "One founder's POV, one continuous world, one integration.",
  "summary": "A 100% AI-made launch film for the Razorpay Agentic Commerce Stack, made for GFF 26.",
  "categories": [
   "AI Film",
   "Video"
  ],
  "cover": {
   "image": "assets/img/p/ace-cover.jpg",
   "video": ""
  },
  "metrics": [],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Introduce one integration for agentic commerce.",
    "body": "Razorpay Agentic Commerce Stack: a launch film for GFF 2026 introducing one integration for agentic commerce across LLMs, concierge agents, WhatsApp and brand assistants."
   },
   {
    "type": "image",
    "image": "assets/img/p/ace-cover.jpg",
    "caption": "ACE: Agentic Commerce Engine | GFF 26",
    "size": "wide"
   },
   {
    "type": "text",
    "label": "The film",
    "title": "Complexity gives way to the agentic era.",
    "body": "Told entirely through one founder's POV in a single continuous world, the film shifts from a grand marble hall to a glowing tech studio as complexity gives way to the agentic era, anchored throughout by a locked, high-contrast visual style built around her."
   },
   {
    "type": "statement",
    "text": "AI was only the production medium."
   },
   {
    "type": "steps",
    "label": "How it was made",
    "title": "100% AI-powered filmmaking, directed like a full-scale production.",
    "items": [
     {
      "title": "Storyboard",
      "body": "Storyboarding and visual exploration to find the world and the character."
     },
     {
      "title": "Art direction",
      "body": "A carefully crafted art direction, locked early so every frame belongs to the same film."
     },
     {
      "title": "Key frames",
      "body": "Designing key frames for every environment and every human character."
     },
     {
      "title": "Generate and direct",
      "body": "Generating and directing the footage itself, frame by frame."
     },
     {
      "title": "Motion and stitch",
      "body": "Creating motion graphics and stitching everything into one cohesive narrative."
     }
    ]
   },
   {
    "type": "text",
    "label": "Under a tight timeline",
    "title": "Every frame intentionally designed and refined.",
    "body": "The film was built under an incredibly tight timeline. The entire film was created using AI, from every environment and human character to the footage itself, and every frame was treated with the same level of creative direction as a full-scale film production."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Claude",
     "Higgsfield",
     "Runway",
     "Gemini",
     "OpenAI",
     "Adobe",
     "Suno"
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": ""
   },
   {
    "name": "Rahul Girish",
    "role": ""
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/255895063/Agentic-Commerce-Engine-Launch-Video"
   }
  ],
  "slug": "agentic-commerce-engine"
 },
 {
  "published": true,
  "featured": false,
  "title": "International Payments Launch Video",
  "order": 7,
  "title_lines": "International\nPayments",
  "card_title": "International\nPayments",
  "client": "Razorpay",
  "year": "2023",
  "category": "Motion graphics · Launch video",
  "role": "Design & Motion",
  "tagline": "Launch video for the import flow of Razorpay International Payments.",
  "summary": "A 40 to 60 second motion graphics film that makes international e-commerce payments simple to follow.",
  "categories": [
   "Video",
   "Motion"
  ],
  "cover": {
   "image": "assets/img/p/intl-cover.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "1000+",
    "label": "organic views"
   },
   {
    "value": "40–60s",
    "label": "film length"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Show how Razorpay lets international businesses accept payments from India.",
    "body": "A dive into the world of international e-commerce payments, focused on Razorpay's solution that lets international businesses accept payments from India and settle in their own currency."
   },
   {
    "type": "text",
    "label": "The approach",
    "title": "Demystify global e-commerce transactions in under a minute.",
    "body": "The challenge was to demystify the technicalities of global e-commerce transactions. The solution was a vibrant 40 to 60 second animation that makes the intricacies of international payments both understandable and visually compelling."
   },
   {
    "type": "statement",
    "text": "Complex financial processes, turned into a visually engaging narrative."
   },
   {
    "type": "text",
    "label": "The craft",
    "title": "Motion graphics and kinetic animation.",
    "body": "The film transforms complex financial processes into a visual narrative using motion graphics and kinetic animation, created with Adobe Illustrator and After Effects. It resonated with the audience, earning over 1000 organic views."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Adobe Illustrator",
     "After Effects"
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": ""
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/185746781/Razorpay-International-Payments-Launch-Video"
   }
  ],
  "slug": "international-payments"
 },
 {
  "published": true,
  "featured": false,
  "title": "Magic Conversations Videos",
  "order": 8,
  "title_lines": "Magic\nConversations",
  "card_title": "Magic\nConversations",
  "client": "Razorpay Magic Checkout",
  "year": "2023",
  "category": "Testimonial films",
  "role": "Design team lead",
  "tagline": "Two merchants on how Magic Checkout changed their business.",
  "summary": "Testimonial films with Isak Fragrances and VS Mani Filter Coffees, shot and edited by a team of young designers learning the craft.",
  "categories": [
   "Video"
  ],
  "cover": {
   "image": "assets/img/p/conv-cover.jpg",
   "video": ""
  },
  "metrics": [],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Merchants in their own words.",
    "body": "A testimonial video project that brings to life the experiences, and the tangible benefits, that two Razorpay clients, Isak Fragrances and VS Mani Filter Coffees, have enjoyed since integrating Magic Checkout into their e-commerce platforms."
   },
   {
    "type": "text",
    "label": "Isak Fragrances",
    "title": "Embracing the digital stage.",
    "body": "The first film was a venture into remote video production. Conducted over Zoom, it was new terrain for the team, pushing them to adapt and innovate. The result is a narrative of how Magic Checkout revolutionised Isak's online sales, told with authenticity and a fresh perspective by budding designers."
   },
   {
    "type": "text",
    "label": "VS Mani Filter Coffees",
    "title": "Learning in the field.",
    "body": "The second film was a different challenge: an on-site shoot at the client's office. It was hands-on learning for the team, who navigated the nuances of location shooting with determination, and the film captures how Magic Checkout transformed the business, seen through the lens of designers learning with every shot and edit."
   },
   {
    "type": "statement",
    "text": "Designers learning to direct, one shot at a time."
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": ""
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/185745413/Magic-Conversations-Videos"
   }
  ],
  "slug": "magic-conversations"
 },
 {
  "published": true,
  "featured": false,
  "title": "Passport For Your Product",
  "order": 9,
  "title_lines": "Passport For\nYour Product",
  "card_title": "Passport For\nYour Product",
  "client": "Razorpay International Payments",
  "year": "2023",
  "category": "AI campaign",
  "role": "Campaign lead",
  "tagline": "AI-generated launch campaign for Razorpay International Payments.",
  "summary": "A launch campaign whose entire design identity was built with a new AI workflow, then taken to YouTube, LinkedIn and Meta.",
  "categories": [
   "Campaign",
   "AI Film"
  ],
  "cover": {
   "image": "assets/img/p/passport-cover.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "50%",
    "label": "view-through rate on LinkedIn"
   },
   {
    "value": "94",
    "label": "leads generated"
   },
   {
    "value": "35%",
    "label": "lower buy rates"
   },
   {
    "value": "60K+",
    "label": "impressions on the behind-the-scenes video"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Make borderless business feel effortless.",
    "body": "Razorpay's Passport For Your Product campaign was a cornerstone of the International Payments launch. Cracking the brief took a new approach: an AI workflow introduced to establish a distinctive campaign design identity, positioning Razorpay as a forerunner in fintech by showing effortless global business expansion."
   },
   {
    "type": "image",
    "image": "assets/img/p/passport-ads.jpg",
    "caption": "Accept payments with 2X security, 2X possibilities, 2X savings",
    "size": "narrow"
   },
   {
    "type": "steps",
    "label": "The process",
    "title": "Where creativity and technology converge.",
    "items": [
     {
      "title": "Imagery",
      "body": "Midjourney conjured the compelling images that formed the campaign's visual backbone.",
      "tools": "Midjourney"
     },
     {
      "title": "Enhancement",
      "body": "Photoshop generative fill extended the images to every required dimension without losing their charm.",
      "tools": "Photoshop"
     },
     {
      "title": "Animation",
      "body": "The stills were set in motion, turning them into a seamless, flowing narrative.",
      "tools": "Kaiber AI"
     },
     {
      "title": "Edit",
      "body": "The voiceover and visuals were brought together to create a cohesive story.",
      "tools": "Adobe Premiere"
     }
    ]
   },
   {
    "type": "text",
    "label": "Performance",
    "title": "High relevance, interaction and reach.",
    "body": "The brand campaign beat expectations with high relevance and interaction rates, leading to 35% lower buy rates. It achieved a 50% view-through rate on LinkedIn and substantial engagement on Meta. Distribution across YouTube, LinkedIn and Meta Ads maximised reach, with 94 leads generated, signalling strong interest in Razorpay International Payments."
   },
   {
    "type": "text",
    "label": "Behind the scenes",
    "title": "The process was content too.",
    "body": "The behind-the-scenes video detailing the process was also well received on LinkedIn: over 60,000 impressions, and comments that appreciated the modern approach of using AI tools to push the boundaries of digital marketing."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Midjourney",
     "Photoshop",
     "Kaiber AI",
     "Adobe Premiere"
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Campaign lead"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/185756345/Passport-For-Your-Products-AI-Gen-Campaign"
   }
  ],
  "slug": "passport-for-your-products"
 },
 {
  "published": true,
  "featured": false,
  "title": "MoneySaver Export Account",
  "order": 10,
  "title_lines": "MoneySaver\nExport Account",
  "card_title": "MoneySaver\nExport Account",
  "client": "Razorpay International Payments",
  "year": "2023",
  "category": "AI launch video",
  "role": "Campaign lead",
  "tagline": "India's first PA/PG with an OPGSP compliant solution, launched with an AI-made film.",
  "summary": "A launch video and digital media strategy for the MoneySaver Export Account, made entirely with AI design tools.",
  "categories": [
   "Campaign",
   "AI Film"
  ],
  "cover": {
   "image": "assets/img/p/money-hero.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "438K+",
    "label": "views on Razorpay's social channels"
   },
   {
    "value": "29.1M",
    "label": "media reach across 32+ stories"
   },
   {
    "value": "70+",
    "label": "high-quality leads"
   },
   {
    "value": "313K",
    "label": "impressions on the behind-the-scenes post"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "A high-stakes launch for Indian exporters.",
    "body": "A launch campaign for the MoneySaver Export Account, marking India's first PA/PG with an OPGSP compliant solution, exclusively for Indian exporters. The project covered an innovative video and a comprehensive digital media strategy, positioning the product as a pivotal solution for exporters."
   },
   {
    "type": "image",
    "image": "assets/img/p/money-hero.jpg",
    "caption": "MoneySaver Export Account: India's first Smart Account for receiving international payments with ease",
    "size": "full"
   },
   {
    "type": "text",
    "label": "The film",
    "title": "A first in the industry, crafted entirely with AI-based design tools.",
    "body": "The video was made with Midjourney, Studio D-ID and ElevenLabs. The goal was to capture the essence of the product: a platform that lets exporters open a bank account in their choice of country in under 5 seconds and save up to 50% on international transfer charges. Motion graphics and kinetic animation carried those points."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Midjourney",
     "Studio D-ID",
     "ElevenLabs"
    ]
   },
   {
    "type": "text",
    "label": "Campaign impact",
    "title": "Razorpay's biggest product launch on its own platforms.",
    "body": "Over 438K views on Razorpay's social channels made it the biggest product launch there. Media coverage, including an exclusive interview on MoneyControl, led to 32+ stories and a reach of 29.1 million. The launch blog saw an 89.62% engagement rate with around 3K views, and the campaign generated over 70 high-quality leads."
   },
   {
    "type": "text",
    "label": "Behind the scenes",
    "title": "Showing the AI workflow in the open.",
    "body": "A behind-the-scenes video detailed the use of AI tools in the campaign's creation. On LinkedIn that post received 1.2K likes, 83 comments and 33 reposts, with 313,315 impressions, and comments from the industry highlighted AI as a game-changer in marketing and B2B payments."
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Campaign lead"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/185754027/MoneySaver-Export-Account-AI-Gen-campaign"
   }
  ],
  "slug": "moneysaver-export-account"
 },
 {
  "published": true,
  "featured": false,
  "title": "Razorpay Payments on WhatsApp",
  "order": 11,
  "title_lines": "Payments on\nWhatsApp",
  "card_title": "Payments on\nWhatsApp",
  "client": "Razorpay",
  "year": "2023",
  "category": "AI campaign",
  "role": "Campaign lead",
  "tagline": "Melancholy: the silent stories of abandoned carts. Shop. Don't abandon.",
  "summary": "A launch film where AI-generated imagery tells sad stories of abandoned carts, then turns them into stories of completion.",
  "categories": [
   "Campaign",
   "AI Film"
  ],
  "cover": {
   "image": "assets/img/p/whatsapp-cover.jpg",
   "video": ""
  },
  "metrics": [
   {
    "value": "95K+",
    "label": "impressions across social channels"
   },
   {
    "value": "10%",
    "label": "engagement rate on Twitter"
   },
   {
    "value": "4.5%",
    "label": "engagement rate on LinkedIn"
   },
   {
    "value": "2000+",
    "label": "businesses expressed interest"
   }
  ],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Launch Razorpay payments on WhatsApp.",
    "body": "The campaign for Razorpay's payment solution on WhatsApp, led from concept to completion: coordinating teams, managing the creative process and using AI technology to make a campaign that is both innovative and emotionally resonant."
   },
   {
    "type": "statement",
    "text": "Shop. Don't abandon."
   },
   {
    "type": "text",
    "label": "The idea",
    "title": "Melancholy.",
    "body": "Brainstorms with the marketing and design teams produced three campaign concepts. The chosen one, \"Melancholy\", delved into the emotive narrative of abandoned shopping carts in the digital realm, each with a story echoing the silent plea, \"Shop. Don't Abandon.\""
   },
   {
    "type": "image",
    "image": "assets/img/p/whatsapp-board.jpg",
    "caption": "AI imagery, the script, and the Photoshop, After Effects and Premiere edit",
    "size": "wide"
   },
   {
    "type": "steps",
    "label": "The process",
    "title": "A solemn start, an upbeat turn.",
    "items": [
     {
      "title": "Imagery",
      "body": "Midjourney created the visual cornerstone: unique, emotionally compelling images of the silent stories of abandoned carts.",
      "tools": "Midjourney"
     },
     {
      "title": "Animation",
      "body": "Static images were brought to life into a flowing, dynamic narrative.",
      "tools": "Kaiber AI"
     },
     {
      "title": "Voice",
      "body": "A professional voiceover artist added a solemn tone that turns optimistic and energetic as Razorpay introduces its solution."
     },
     {
      "title": "Edit",
      "body": "Visuals and voiceover were edited together, with the visual style blending Razorpay blue and WhatsApp green.",
      "tools": "After Effects · Premiere"
     }
    ]
   },
   {
    "type": "text",
    "label": "Results",
    "title": "The highest engagement rates on Twitter and LinkedIn.",
    "body": "With PR efforts, the launch video amassed over 95K impressions across social channels, with the highest engagement rates on Twitter (10%) and LinkedIn (4.5%). The accompanying blog captivated 6K+ unique readers, and 2000+ businesses expressed interest in the product, including a substantial number of existing Razorpay merchants."
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Midjourney",
     "Kaiber AI",
     "Photoshop",
     "After Effects",
     "Premiere"
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": "Campaign lead"
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/185779105/Razorpay-Payments-on-WhatsApp"
   }
  ],
  "slug": "payments-on-whatsapp"
 },
 {
  "published": true,
  "featured": false,
  "title": "Grofers Logo Guidelines",
  "order": 12,
  "title_lines": "Grofers\nLogo Guidelines",
  "card_title": "Grofers\nLogo Guidelines",
  "client": "Grofers",
  "year": "2021",
  "category": "Identity system",
  "role": "Art Direction · Graphic Design",
  "tagline": "How the Grofers logo behaves: space, shades, placement and hierarchy.",
  "summary": "Logo usage guidelines for Grofers, covering clear space, colourways, placement, typographic hierarchy and in-app creative templates.",
  "categories": [
   "Brand & Identity"
  ],
  "cover": {
   "image": "assets/img/p/grofers-cover.jpg",
   "video": ""
  },
  "metrics": [],
  "sections": [
   {
    "type": "text",
    "label": "The brief",
    "title": "Give every team one way to use the logo.",
    "body": "A guideline document for the Grofers brand so that the logo, and the creatives built around it, look consistent wherever they appear. Created in Adobe Illustrator."
   },
   {
    "type": "image",
    "image": "assets/img/p/grofers-1.jpg",
    "caption": "Brand campaign layouts",
    "size": "narrow"
   },
   {
    "type": "image",
    "image": "assets/img/p/grofers-2.jpg",
    "caption": "Meet the logo, clear space, and the go-to shades",
    "size": "narrow"
   },
   {
    "type": "image",
    "image": "assets/img/p/grofers-3.jpg",
    "caption": "Logo placement and lock-ups",
    "size": "narrow"
   },
   {
    "type": "image",
    "image": "assets/img/p/grofers-4.jpg",
    "caption": "Logo placement in layouts, and hierarchy examples",
    "size": "narrow"
   },
   {
    "type": "image",
    "image": "assets/img/p/grofers-5.jpg",
    "caption": "Typography dos, hierarchy examples and creatives",
    "size": "narrow"
   },
   {
    "type": "image",
    "image": "assets/img/p/grofers-6.jpg",
    "caption": "In-app templates",
    "size": "wide"
   },
   {
    "type": "tools",
    "label": "Stack",
    "items": [
     "Adobe Illustrator"
    ]
   }
  ],
  "team": [
   {
    "name": "Vibhor Mathur",
    "role": ""
   },
   {
    "name": "Zahid Shaikh",
    "role": ""
   }
  ],
  "awards": [],
  "links": [
   {
    "label": "Behance case study",
    "url": "https://www.behance.net/gallery/123079157/grofers-logo-guidelines"
   }
  ],
  "slug": "grofers-logo-guidelines"
 }
];
window.EXPERIMENTS = [
 {
  "title": "Habitats without the life",
  "slug": "habitats",
  "published": true,
  "order": 1,
  "year": "2023",
  "medium": [
   "AI art"
  ],
  "tools": "Stable Diffusion, ControlNet",
  "title_lines": "Habitats\nwithout\nthe life",
  "tagline": "Landscapes that carry the silhouette of the creatures that belong in them.",
  "summary": "AI landscapes built from animal silhouettes with Stable Diffusion and ControlNet.",
  "cover": {
   "image": "assets/img/lab/habitats-02.jpg",
   "video": ""
  },
  "sections": [
   {
    "type": "text",
    "label": "The idea",
    "title": "Wildlife and habitat are one picture.",
    "body": "A visual representation of the interconnectedness between wildlife and their habitats, and a reminder of the delicate balance of our ecosystems.\n\nUsing Stable Diffusion and its ControlNet feature, I made landscapes that blend the essence of iconic creatures with their natural environments."
   },
   {
    "type": "text",
    "label": "The method",
    "title": "Start from a silhouette, grow a landscape.",
    "body": "The control images are plain black-and-white silhouettes: a bear, a camel, an elephant and a rhino. Each generated landscape sits next to the shape it was built from, so you can see how the creature's outline organises the terrain."
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-01.jpg",
      "caption": "Bear: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-02.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-03.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-04.jpg",
      "caption": "Camel: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-05.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-06.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-07.jpg",
      "caption": "Elephant: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-08.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-09.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "image_grid",
    "columns": "3",
    "images": [
     {
      "image": "assets/img/lab/habitats-10.jpg",
      "caption": "Rhino: control silhouette"
     },
     {
      "image": "assets/img/lab/habitats-11.jpg",
      "caption": "Result"
     },
     {
      "image": "assets/img/lab/habitats-12.jpg",
      "caption": "Result"
     }
    ]
   },
   {
    "type": "tools",
    "label": "Tools",
    "items": [
     "Stable Diffusion",
     "ControlNet"
    ]
   }
  ],
  "links": [
   {
    "label": "Original post (Dec 2023)",
    "url": "https://www.onlyvibhor.com/post/habitats-without-the-life"
   }
  ]
 },
 {
  "title": "Absolut Landscapes",
  "slug": "absolut",
  "published": true,
  "order": 2,
  "year": "2023",
  "medium": [
   "AI art"
  ],
  "tools": "SMUGO.ai, Stable Diffusion, ControlNet (Canny)",
  "title_lines": "Absolut\nLandscapes",
  "tagline": "A modern AI take on a campaign built around one bottle shape.",
  "summary": "Landscapes shaped by the Absolut bottle, made with Stable Diffusion and ControlNet.",
  "cover": {
   "image": "assets/img/lab/absolut-4.jpg",
   "video": ""
  },
  "sections": [
   {
    "type": "text",
    "label": "The reference",
    "title": "Absolut has built a campaign around one shape for decades.",
    "body": "Absolut Vodka's long-running advertising features the distinctive shape of its bottle, promoting artistic interpretations of it. Its collaborations with visual artists date back to the 1980s, and Andy Warhol once said: *\"I love the bottle. I'd like to do something.\"*\n\nA modern AI version of the idea felt like the obvious next experiment. This is a personal exploration inspired by that campaign."
   },
   {
    "type": "text",
    "label": "The method",
    "title": "The bottle becomes the structure.",
    "body": "I used SMUGO.ai, a free platform with an interface close to Automatic1111 that offers Stable Diffusion's img2img, ControlNet and HiResFix.\n\nThe shape of the bottle went into ControlNet using the Canny processor, with some prompt engineering on top. The images are low resolution because I did not have access to my own PC when I made them."
   },
   {
    "type": "image_grid",
    "columns": "2",
    "images": [
     {
      "image": "assets/img/lab/absolut-1.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-2.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-3.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-4.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-5.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-6.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-7.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/lab/absolut-8.jpg",
      "caption": ""
     }
    ]
   },
   {
    "type": "tools",
    "label": "Tools",
    "items": [
     "SMUGO.ai",
     "Stable Diffusion",
     "ControlNet (Canny)",
     "img2img",
     "HiResFix"
    ]
   }
  ],
  "links": [
   {
    "label": "Original post (Nov 2023)",
    "url": "https://www.onlyvibhor.com/post/stable-diffusion-ai-and-controlnet"
   }
  ]
 },
 {
  "title": "AI Experiments",
  "slug": "ai-experiments",
  "published": true,
  "order": 3,
  "year": "2023",
  "medium": [
   "AI art"
  ],
  "tools": "Midjourney, Stable Diffusion, RunwayML, PIKA Labs, Kaiber AI",
  "title_lines": "AI\nExperiments",
  "tagline": "AI images, videos, animations and more.",
  "summary": "A creative AI journey blending technology and artistry: landscapes, roses and video experiments across Midjourney, Stable Diffusion, RunwayML, PIKA Labs and Kaiber AI.",
  "cover": {
   "image": "assets/img/p/aiexp-10.jpg",
   "video": ""
  },
  "sections": [
   {
    "type": "text",
    "label": "The journey",
    "title": "Blending technology and artistry.",
    "body": "A creative AI journey blending technology and artistry to craft stunning visuals. From AI-generated images of roses to innovative video experiments, an exploration of the limitless possibilities of Midjourney, Stable Diffusion, RunwayML, PIKA Labs, Kaiber AI and other tools."
   },
   {
    "type": "image_grid",
    "columns": 2,
    "images": [
     {
      "image": "assets/img/p/aiexp-10.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/p/aiexp-11.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/p/aiexp-12.jpg",
      "caption": ""
     },
     {
      "image": "assets/img/p/aiexp-13.jpg",
      "caption": ""
     }
    ]
   },
   {
    "type": "image",
    "image": "assets/img/p/aiexp-14.jpg",
    "caption": "",
    "size": "narrow"
   },
   {
    "type": "tools",
    "label": "Tools",
    "items": [
     "Midjourney",
     "Stable Diffusion",
     "RunwayML",
     "PIKA Labs",
     "Kaiber AI"
    ]
   }
  ],
  "links": [
   {
    "label": "Behance project",
    "url": "https://www.behance.net/gallery/185757595/AI-Experiments"
   }
  ]
 }
];
