#!/usr/bin/env python3
"""Bundle CMS content into content/content.js.

Reads  content/site.json, content/about.json, content/toolkit.json, content/mentorship.json,
       content/projects/*.json, content/experiments/*.json
Writes content/content.js  (window.SITE, window.ABOUT, window.TOOLKIT, window.MENTORSHIP, window.PROJECTS, window.EXPERIMENTS)

Run after editing content:   python scripts/build_content.py
Netlify/Vercel run it automatically (see netlify.toml).
"""
import hashlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def check_asset(ref, owner, problems):
    if not ref or ref.startswith(("http://", "https://", "data:")):
        return
    if not (ROOT / ref.lstrip("/")).exists():
        problems.append(f"{owner}: missing file {ref}")


def check_entry(p, owner, problems):
    cover = p.get("cover") or {}
    check_asset(cover.get("image"), owner, problems)
    check_asset(cover.get("video"), owner, problems)
    for s in p.get("sections", []):
        t = s.get("type")
        if t == "image":
            check_asset(s.get("image"), owner, problems)
        elif t == "image_grid":
            for i in s.get("images", []):
                check_asset(i.get("image"), owner, problems)
        elif t == "clips":
            for c in s.get("clips", []):
                check_asset(c.get("video"), owner, problems)
        elif t == "video":
            check_asset(s.get("poster"), owner, problems)
            if not s.get("url", "").startswith(("http://", "https://")):
                check_asset(s.get("url"), owner, problems)


def collect(folder, label, problems):
    items = []
    for p in sorted((CONTENT / folder).glob("*.json")):
        data = load(p)
        if not data.get("slug"):
            data["slug"] = p.stem
        if not data.get("published", True):
            print(f"  draft, skipped: {label} '{data['slug']}'")
            continue
        items.append(data)
    slugs = [p["slug"] for p in items]
    dupes = {s for s in slugs if slugs.count(s) > 1}
    if dupes:
        sys.exit(f"Duplicate {label} slugs: {', '.join(sorted(dupes))}")
    items.sort(key=lambda p: (p.get("order", 999), p["title"]))
    for p in items:
        check_entry(p, f"{label} '{p['slug']}'", problems)
    return items


def stamp_pages():
    """Cache-bust: ?v=<hash of css/js/content> on every asset link in the html pages."""
    h = hashlib.md5()
    for f in sorted([ROOT / "content" / "content.js", *(ROOT / "assets").glob("css/*.css"), *(ROOT / "assets").glob("js/*.js")]):
        h.update(f.read_bytes())
    v = h.hexdigest()[:8]
    for page in ROOT.glob("*.html"):
        t = page.read_text(encoding="utf-8")
        n = re.sub(r'((?:assets/(?:css|js)/[a-z]+\.(?:css|js)|content/content\.js))(?:\?v=[0-9a-f]+)?"', lambda m: f'{m.group(1)}?v={v}"', t)
        if n != t:
            page.write_text(n, encoding="utf-8")


def main():
    problems = []
    site = load(CONTENT / "site.json")
    about = load(CONTENT / "about.json")
    projects = collect("projects", "project", problems)
    experiments = collect("experiments", "experiment", problems)

    for s in (site.get("hero", {}).get("slides") or []):
        check_asset(s.get("image"), "site hero", problems)
    check_asset(about.get("portrait"), "about portrait", problems)

    mentorship = load(CONTENT / "mentorship.json")
    for e in (mentorship.get("events") or {}).get("items", []):
        check_asset(e.get("image"), "mentorship event", problems)
    for g in (mentorship.get("gallery") or {}).get("items", []):
        check_asset(g.get("image"), "mentorship gallery", problems)

    toolkit = load(CONTENT / "toolkit.json")
    for t in toolkit.get("tools", []):
        check_asset(t.get("hero"), "toolkit tool " + t.get("name", ""), problems)
        for g in t.get("gallery", []):
            check_asset(g, "toolkit tool " + t.get("name", ""), problems)
    for i in (toolkit.get("interactive") or {}).get("items", []):
        check_asset(i.get("image"), "toolkit interactive", problems)
    for i in (toolkit.get("learn") or {}).get("images", []):
        check_asset(i.get("image"), "toolkit learn", problems)
    check_asset((toolkit.get("learn") or {}).get("wide"), "toolkit learn", problems)

    out = CONTENT / "content.js"
    payload = (
        "/* Generated by scripts/build_content.py. Do not edit by hand. */\n"
        "window.SITE = " + json.dumps(site, ensure_ascii=False, indent=1) + ";\n"
        "window.ABOUT = " + json.dumps(about, ensure_ascii=False, indent=1) + ";\n"
        "window.MENTORSHIP = " + json.dumps(mentorship, ensure_ascii=False, indent=1) + ";\n"
        "window.TOOLKIT = " + json.dumps(toolkit, ensure_ascii=False, indent=1) + ";\n"
        "window.PROJECTS = " + json.dumps(projects, ensure_ascii=False, indent=1) + ";\n"
        "window.EXPERIMENTS = " + json.dumps(experiments, ensure_ascii=False, indent=1) + ";\n"
    )
    out.write_text(payload, encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}: {len(projects)} project(s), {len(experiments)} experiment(s)")
    stamp_pages()
    for pr in problems:
        print("  WARNING", pr)


if __name__ == "__main__":
    main()
